# Homework Assignment - Lesson 3: Data Transformation with dplyr - Part 1

**Student Name:** Alejandro De Santiago Palomares Salinas

**Due Date:** 09/21/2025

**Objective:** Learn to use dplyr functions (`select()`, `filter()`, `arrange()`) and the pipe operator (`%>%`) for data transformation and analysis.

---

## Instructions

- Complete all tasks in this notebook
- Use the pipe operator (`%>%`) wherever possible to chain operations
- Ensure your code is well-commented and easy to understand
- Run all cells to verify your code works correctly
- Answer all reflection questions at the end

---

## Part 1: Data Import and Setup

In this section, you'll import the retail transactions dataset and perform initial exploration.

**Dataset:** `retail_transactions.csv` - This dataset contains transaction records from a retail business with information about customers, products, dates, amounts, and quantities.

In [9]:
# Load required libraries
library(tidyverse)

# Set working directory if needed
setwd("/workspaces/assignment-2-version3-Aledesan-utsa/data")

# Task 1.1: Import the retail_transactions.csv file
# Create a data frame named 'transactions'
# Note: Import the retail_transactions.csv file

# Your code here:
transactions <- read.csv("retail_transactions.csv")

# Display success message
cat("Data imported successfully!\n")
cat("Dataset dimensions:", nrow(transactions), "rows x", ncol(transactions), "columns\n")

Data imported successfully!
Dataset dimensions: 500 rows x 9 columns

In [10]:
# Task 1.2: Initial Exploration

# Display the first 10 rows
cat("First 10 rows of the dataset:\n")
head(transactions, 10)


# Check the structure of the dataset
cat("\nDataset structure:\n")
str(transactions)


# Display column names and their data types
cat("\nColumn names:\n")
colnames(transactions)

First 10 rows of the dataset:

   TransactionID CustomerID CustomerName CustomerCity ProductName
1   1            81         Customer 39  Chicago      Adidas Jacket
2   2            13         Customer 63  Philadelphia Samsung TV
3   3            18         Customer 98  Chicago      Adidas Jacket
4   4            76         Customer 39  Houston      Dell Laptop
5   5            86         Customer 45  New York     Nike Shoes
6   6            37         Customer 8   Philadelphia Adidas Jacket
7   7            45         Customer 83  New York     HP Printer
8   8            11         Customer 60  Chicago      Samsung TV
9   9            13         Customer 69  Houston      iPhone 14
10 10            55         Customer 24  Chicago      Sony Headphones
   ProductCategory TotalAmount Quantity TransactionDate
1  Clothing         632.39     3        2024-03-09
2  Music            114.28     3        2024-12-08
3  Computers       1289.24     7        2024-01-22
4  Computers        885.40     2        2024-07-02
5  Computers         95.95     5        2024-08-13
6  Electronics     1126.34     2        2024-04-15
7  Clothing          78.71     3        2024-05-02
8  Music            871.93     3        2024-04-30
9  Music           1347.56     8        2024-08-08
10 Books            633.51     1        2024-06-23

Dataset structure:
'data.frame':	500 obs. of  9 variables:
 $ TransactionID  : int  1 2 3 4 5 6 7 8 9 10 ...
 $ CustomerID     : int  81 13 18 76 86 37 45 11 13 55 ...
 $ CustomerName   : chr  "Customer 39" "Customer 63" "Customer 98" "Customer 39" ...
 $ CustomerCity   : chr  "Chicago" "Philadelphia" "Chicago" "Houston" ...
 $ ProductName    : chr  "Adidas Jacket" "Samsung TV" "Adidas Jacket" "Dell Laptop" ...
 $ ProductCategory: chr  "Clothing" "Music" "Computers" "Computers" ...
 $ TotalAmount    : num  632 114 1289 885 96 ...
 $ Quantity       : int  3 3 7 2 5 2 3 3 8 1 ...
 $ TransactionDate: chr  "2024-03-09" "2024-12-08" "2024-01-22" "2024-07-02" ...

Column names:

[1] "TransactionID"   "CustomerID"      "CustomerName"    "CustomerCity"
[5] "ProductName"     "ProductCategory" "TotalAmount"     "Quantity"
[9] "TransactionDate"

## Part 2: Column Selection with `select()`

Practice different methods of selecting columns from your dataset.

In [12]:
# Task 2.1: Basic Selection
# Create 'basic_info' with TransactionID, CustomerID, ProductName, and TotalAmount

basic_info <- transactions %>%
select(TransactionID, CustomerID, ProductName,TotalAmount)
                                       
                                       
print("Selected Columns (TransactionID, CustomerID, ProductName,TotalAmount):")
print(basic_info)               # Result has only 4 columns instead of original 8


# Display the result
cat("Basic info dataset (first 5 rows):\n")
head(basic_info, 5)

[1] "Selected Columns (TransactionID, CustomerID, ProductName,TotalAmount):"
    TransactionID CustomerID     ProductName TotalAmount
1               1         81   Adidas Jacket      632.39
2               2         13      Samsung TV      114.28
3               3         18   Adidas Jacket     1289.24
4               4         76     Dell Laptop      885.40
5               5         86      Nike Shoes       95.95
6               6         37   Adidas Jacket     1126.34
7               7         45      HP Printer       78.71
8               8         11      Samsung TV      871.93
9               9         13       iPhone 14     1347.56
10             10         55 Sony Headphones      633.51
11             11        100      HP Printer      572.43
12             12         89   Adidas Jacket     1208.43
13             13         56     Dell Laptop     1337.94
14             14         19      Nike Shoes       32.29
15             15          1      Nike Shoes      602.79
16             16         78      HP Printer     1476.49
17             17          2 Sony Headphones      520.91
18             18          5     Dell Laptop     1012.57
19             19          7 Sony Headphones      834.08
20             20         27     Dell Laptop     1176.07
21             21         31      HP Printer      259.44
22             22         80       iPhone 14     1424.99
23             23         57      HP Printer      897.63
24             24         88      Nike Shoes     1168.05
25             25         97       iPhone 14      999.24
26             26         34       iPhone 14      504.96
27             27          6      HP Printer       88.45
28             28         54   Adidas Jacket      703.88
29             29          3      Samsung TV     1392.13
30             30         98      Samsung TV      294.82
31             31         11   Adidas Jacket     1219.37
32             32         21 Sony Headphones     1416.35
33             33         60       iPhone 14       82.98
34             34         62   Adidas Jacket      887.44
35             35         24      Samsung TV      536.69
36             36         47   Adidas Jacket      871.96
37             37         66      Nike Shoes     1080.28
38             38         55   Adidas Jacket       42.27
39             39         36 Sony Headphones       50.25
40             40         30 Sony Headphones      744.85
41             41         60       iPhone 14      247.98
42             42         59 Sony Headphones     1158.09
43             43         27 Sony Headphones      817.22
44             44          7       iPhone 14     1136.57
45             45          1       iPhone 14     1206.70
46             46         40      HP Printer      229.81
47             47         87      HP Printer       57.22
48             48         71       iPhone 14      935.30
49             49         17     Dell Laptop     1220.59
50             50         92      Nike Shoes      808.93
51             51         20      HP Printer     1397.43
52             52         31   Adidas Jacket     1246.39
53             53         32   Adidas Jacket      502.72
54             54         67      Nike Shoes      475.40
55             55         17 Sony Headphones      962.80
56             56         43   Adidas Jacket      124.82
57             57         84      Samsung TV      487.41
58             58         31   Adidas Jacket      952.01
59             59          9      Samsung TV      941.02
60             60         61      Nike Shoes      597.96
61             61         87     Dell Laptop     1491.96
62             62         32      Samsung TV     1424.38
63             63         88   Adidas Jacket      216.52
64             64          9   Adidas Jacket      913.13
65             65         94      Samsung TV      781.85
66             66         21   Adidas Jacket      960.77
67             67         23     Dell Laptop      304.06
68             68         28     Dell Laptop      140.76
69             69         70      Nike Shoes     1370.57
70             70         61       iPhone 14     1150.96
71             71         20     Dell Laptop     1411.95
72             72         15 Sony Headphones      162.98
73             73         50 Sony Headphones      906.83
74             74         57      Samsung TV      875.19
75             75         91   Adidas Jacket      378.17
76             76         35       iPhone 14      963.57
77             77         21      Samsung TV      329.58
78             78         59       iPhone 14     1124.15
79             79         52       iPhone 14      178.22
80             80         12       iPhone 14     1184.65
81             81         86     Dell Laptop       96.83
82             82         69   Adidas Jacket      570.82
83             83         65       iPhone 14      144.20
84             84         41       iPhone 14     1471.59
85             85         49      Nike Shoes      420.46
86             86         28   Adidas Jacket      722.72
87             87          3     Dell Laptop      191.97
88             88         96   Adidas Jacket      695.21
89             89         61      HP Printer      973.31
90             90         12     Dell Laptop      931.78
91             91         54      HP Printer      721.24
92             92          6       iPhone 14     1099.52
93             93         36   Adidas Jacket      676.93
94             94         85     Dell Laptop      521.86
95             95         51   Adidas Jacket     1349.26
96             96         90      Samsung TV      721.25
97             97          3   Adidas Jacket       68.81
98             98         46      Nike Shoes      789.00
99             99         54      Nike Shoes      129.02
100           100         66     Dell Laptop     1375.08
101           101          9      Nike Shoes      507.05
102           102         38 Sony Headphones      312.95
103           103         41 Sony Headphones      486.77
104           104         52     Dell Laptop     1428.17
105           105         81       iPhone 14      562.58
106           106         85     Dell Laptop      216.81
107           107         85   Adidas Jacket      565.04
108           108         41      HP Printer       91.71
109           109         60   Adidas Jacket     1016.07
110           110         51      Samsung TV      537.87
111           111         53       iPhone 14      431.35
112           112         99      Nike Shoes      316.79
113           113         98      HP Printer      443.01
114           114          3      Nike Shoes      445.93
115           115         20 Sony Headphones      768.14
116           116         22       iPhone 14      133.85
117           117         88   Adidas Jacket      268.52
118           118         43     Dell Laptop     1064.21
119           119         49      HP Printer     1043.34
120           120         29      Samsung TV      681.53
121           121         76 Sony Headphones      847.13
122           122         35   Adidas Jacket     1414.89
123           123         87   Adidas Jacket      292.25
124           124         78     Dell Laptop     1144.26
125           125         57       iPhone 14     1075.51
126           126         31     Dell Laptop      179.96
127           127         54   Adidas Jacket     1208.75
128           128         39   Adidas Jacket     1031.13
129           129         88   Adidas Jacket     1231.83
130           130         40     Dell Laptop      103.93
131           131         98   Adidas Jacket      869.20
132           132         80   Adidas Jacket      649.12
133           133         65 Sony Headphones     1326.27
134           134         22      Samsung TV      887.40
135           135         14      HP Printer      641.43
136           136         99      HP Printer     1487.44
137           137         14      HP Printer      463.25
138           138         59 Sony Headphones     1274.62
139           139         67 Sony Headphones     1154.62
140           140         70      Samsung TV      488.05
141           141         45   Adidas Jacket      965.32
142           142         75 Sony Headphones     1442.78
143           143         91      Samsung TV      688.87
144           144         93      Samsung TV     1368.21
145           145         11       iPhone 14      289.58
146           146         66       iPhone 14      361.78
147           147         60      Nike Shoes     1001.65
148           148         76       iPhone 14     1192.22
149           149         57     Dell Laptop      253.81
150           150         64 Sony Headphones     1499.52
151           151         88 Sony Headphones      827.63
152           152         24      HP Printer     1109.74
153           153         97      Samsung TV     1169.26
154           154         18 Sony Headphones     1491.62
155           155         21      Nike Shoes      491.01
156           156         86      Samsung TV      493.53
157           157         83      Nike Shoes      134.15
158           158         66   Adidas Jacket     1280.20
159           159         81 Sony Headphones      491.87
160           160         55       iPhone 14      163.68
161           161         63      Nike Shoes      299.82
162           162         68      Samsung TV      414.51
163           163         74      Nike Shoes      770.42
164           164         43      Samsung TV     1118.96
165           165         14     Dell Laptop      499.81
166           166         78     Dell Laptop      696.28
167           167         26 Sony Headphones      997.09
168           168         11      HP Printer      625.59
169           169         89 Sony Headphones     1322.63
170           170         95      Samsung TV     1365.47
171           171         31 Sony Headphones      242.68
172           172         31     Dell Laptop     1220.70
173           173         43      Nike Shoes     1064.89
174           174        100      HP Printer      713.34
175           175         89      Nike Shoes      587.96
176           176         31      HP Printer      162.68
177           177         87 Sony Headphones      425.44
178           178         42 Sony Headphones     1345.51
179           179         14      HP Printer      927.99
180           180         50     Dell Laptop     1316.78
181           181         17       iPhone 14      314.66
182           182         70       iPhone 14      453.17
183           183          5      Nike Shoes      616.11
184           184         83      HP Printer     1374.15
185           185         43 Sony Headphones      726.74
186           186         76      Samsung TV      569.47
187           187         64       iPhone 14     1488.95
188           188         35 Sony Headphones      782.31
189           189         15      Nike Shoes     1176.03
190           190         56     Dell Laptop      180.03
191           191        100      HP Printer      628.76
192           192         86 Sony Headphones      462.32
193           193         77     Dell Laptop      490.24
194           194         78      Samsung TV      245.20
195           195         70   Adidas Jacket      869.66
196           196         11      Nike Shoes     1428.35
197           197         30     Dell Laptop      571.85
198           198         67   Adidas Jacket     1126.44
199           199          9      Nike Shoes      322.00
200           200         15      Samsung TV      867.61
201           201          7       iPhone 14      979.23
202           202          4   Adidas Jacket     1154.91
203           203         32   Adidas Jacket     1011.00
204           204         12 Sony Headphones      446.82
205           205         89   Adidas Jacket      644.95
206           206         96       iPhone 14      525.91
207           207         79       iPhone 14      904.49
208           208         30       iPhone 14       81.27
209           209         27      HP Printer      551.16
210           210          8     Dell Laptop      890.11
211           211         27      Samsung TV      391.17
212           212         79     Dell Laptop     1437.43
213           213         70       iPhone 14      866.79
214           214         49      Nike Shoes      514.75
215           215         51      HP Printer      847.22
216           216         33      Samsung TV      493.89
217           217         85      HP Printer     1393.51
218           218         24     Dell Laptop      957.29
219           219         23   Adidas Jacket      235.06
220           220         78      Samsung TV      820.90
221           221         24 Sony Headphones      424.71
222           222         62      Samsung TV      623.34
223           223         41 Sony Headphones      529.65
224           224         31      Samsung TV      116.06
225           225          3 Sony Headphones     1133.73
226           226         85     Dell Laptop      215.33
227           227         20   Adidas Jacket      667.50
228           228         28   Adidas Jacket      459.68
229           229         37     Dell Laptop     1138.70
230           230          5      Samsung TV      533.08
231           231         16   Adidas Jacket     1445.64
232           232         91     Dell Laptop     1470.30
233           233         23   Adidas Jacket      825.83
234           234         96 Sony Headphones     1034.45
235           235         94      Samsung TV      940.10
236           236          6     Dell Laptop     1024.36
237           237         62      HP Printer     1403.78
238           238          7 Sony Headphones      589.71
239           239         79      HP Printer      769.09
240           240         62      HP Printer      178.55
241           241         18     Dell Laptop      491.55
242           242         41 Sony Headphones      261.12
243           243         46 Sony Headphones     1423.52
244           244         79     Dell Laptop     1453.94
245           245          3      Nike Shoes       82.05
246           246         51   Adidas Jacket     1060.51
247           247          7      HP Printer      546.49
248           248         98   Adidas Jacket     1015.05
249           249         95       iPhone 14      394.12
250           250          1      HP Printer      237.79
251           251         70   Adidas Jacket      277.70
252           252         64     Dell Laptop      305.12
253           253         30     Dell Laptop     1153.30
254           254         67      HP Printer     1027.15
255           255         78     Dell Laptop      535.79
256           256         51     Dell Laptop      883.89
257           257          5      HP Printer     1249.30
258           258         43       iPhone 14      720.84
259           259         23   Adidas Jacket     1333.49
260           260         56   Adidas Jacket      521.39
261           261         27      HP Printer     1422.31
262           262          4      Nike Shoes      360.99
263           263         69   Adidas Jacket      330.42
264           264         76      Nike Shoes     1365.62
265           265         79      Samsung TV      715.21
266           266         33     Dell Laptop     1376.67
267           267         90   Adidas Jacket      216.36
268           268         71      HP Printer     1105.76
269           269         88      Nike Shoes      238.90
270           270         84   Adidas Jacket      406.06
271           271         89      HP Printer     1070.57
272           272         20      HP Printer      895.48
273           273         81 Sony Headphones      304.54
274           274         91   Adidas Jacket     1132.28
275           275        100      Samsung TV       36.37
276           276         35   Adidas Jacket      314.71
277           277         48      HP Printer     1286.07
278           278         73      Samsung TV     1270.57
279           279         93      Samsung TV      654.35
280           280         17      HP Printer       77.02
281           281          7 Sony Headphones     1295.11
282           282         48     Dell Laptop       37.33
283           283         77      Samsung TV      728.18
284           284         82      Nike Shoes     1094.01
285           285         40      HP Printer      518.49
286           286         34      Nike Shoes     1380.35
287           287         11      Samsung TV      695.28
288           288         78       iPhone 14      393.37
289           289         16      Samsung TV      936.96
290           290         19       iPhone 14      266.67
291           291          9   Adidas Jacket     1316.92
292           292         29      HP Printer      834.69
293           293         73       iPhone 14     1284.33
294           294          2      Nike Shoes     1104.69
295           295         40      Nike Shoes      938.98
296           296         56      Samsung TV       54.92
297           297          7       iPhone 14     1487.43
298           298         57      Samsung TV      599.98
299           299         36      Samsung TV      708.66
300           300         85      Samsung TV      664.62
301           301         23 Sony Headphones      206.62
302           302        100      Samsung TV      238.82
303           303         95      Nike Shoes      992.51
304           304         28   Adidas Jacket      502.01
305           305         80      HP Printer      583.86
306           306         89      Nike Shoes      184.44
307           307         36      HP Printer      116.39
308           308          9      HP Printer      726.38
309           309         67      Nike Shoes      792.50
310           310         60      Nike Shoes      323.46
311           311         55     Dell Laptop      996.67
312           312         10      Samsung TV     1364.74
313           313         36      Samsung TV      803.93
314           314         73     Dell Laptop      798.78
315           315          1   Adidas Jacket       27.66
316           316         65 Sony Headphones      697.35
317           317         73      Nike Shoes     1407.51
318           318         27       iPhone 14       64.58
319           319         31      Samsung TV      411.66
320           320         67       iPhone 14      435.02
321           321         43      Nike Shoes     1230.65
322           322         83 Sony Headphones      539.52
323           323         33 Sony Headphones      357.76
324           324          6       iPhone 14      139.91
325           325         26      Samsung TV       41.59
326           326         43      Nike Shoes      760.69
327           327         52      Samsung TV     1165.45
328           328         24      Nike Shoes     1349.46
329           329         20      Nike Shoes      619.12
330           330         52   Adidas Jacket      469.06
331           331         52      Nike Shoes      286.74
332           332         42   Adidas Jacket      361.38
333           333         54      Nike Shoes      179.93
334           334         77      Samsung TV     1240.02
335           335         64     Dell Laptop     1318.32
336           336         82      Nike Shoes     1220.45
337           337         29   Adidas Jacket     1027.87
338           338         29      Samsung TV      784.41
339           339         41      Nike Shoes      220.97
340           340         54     Dell Laptop     1005.32
341           341         47 Sony Headphones     1469.91
342           342         16      Nike Shoes      318.62
343           343         68     Dell Laptop     1007.80
344           344         54 Sony Headphones     1222.95
345           345         44      Samsung TV     1446.47
346           346         64      Nike Shoes      916.81
347           347         54     Dell Laptop      910.46
348           348         94       iPhone 14     1011.00

  TransactionID CustomerID ProductName   TotalAmount
1 1             81         Adidas Jacket  632.39
2 2             13         Samsung TV     114.28
3 3             18         Adidas Jacket 1289.24
4 4             76         Dell Laptop    885.40
5 5             86         Nike Shoes      95.95

In [14]:
# Task 2.2: Range Selection
# Create 'customer_details' with all columns from CustomerID to CustomerCity (inclusive)

customer_details <- transactions %>%
 select(CustomerID:CustomerCity)           
print("Selected Columns by Range (CustomerID to CustomerCity):")
print(customer_details)


# Display the result
cat("Customer details (first 5 rows):\n")
head(customer_details, 5)

[1] "Selected Columns by Range (CustomerID to CustomerCity):"
    CustomerID CustomerName CustomerCity
1           81  Customer 39      Chicago
2           13  Customer 63 Philadelphia
3           18  Customer 98      Chicago
4           76  Customer 39      Houston
5           86  Customer 45     New York
6           37   Customer 8 Philadelphia
7           45  Customer 83     New York
8           11  Customer 60      Chicago
9           13  Customer 69      Houston
10          55  Customer 24      Chicago
11         100  Customer 95 Philadelphia
12          89  Customer 22 Philadelphia
13          56  Customer 62      Phoenix
14          19 Customer 100      Phoenix
15           1  Customer 52     New York
16          78  Customer 20      Chicago
17           2  Customer 38     New York
18           5  Customer 15      Phoenix
19           7   Customer 1      Phoenix
20          27  Customer 57      Chicago
21          31   Customer 1      Houston
22          80   Customer 4     New York
23          57  Customer 50      Chicago
24          88  Customer 30      Phoenix
25          97  Customer 17     New York
26          34   Customer 7 Philadelphia
27           6  Customer 27 Philadelphia
28          54  Customer 41  Los Angeles
29           3  Customer 23     New York
30          98  Customer 48      Houston
31          11  Customer 30      Chicago
32          21  Customer 62      Chicago
33          60  Customer 65 Philadelphia
34          62  Customer 26      Houston
35          24  Customer 47     New York
36          47  Customer 82     New York
37          66  Customer 93      Phoenix
38          55  Customer 61     New York
39          36  Customer 83  Los Angeles
40          30  Customer 73      Houston
41          60   Customer 9      Phoenix
42          59  Customer 20      Chicago
43          27  Customer 74      Houston
44           7  Customer 42      Chicago
45           1  Customer 28 Philadelphia
46          40  Customer 56      Houston
47          87  Customer 87      Chicago
48          71  Customer 18 Philadelphia
49          17  Customer 73 Philadelphia
50          92  Customer 83      Chicago
51          20  Customer 26      Phoenix
52          31  Customer 33     New York
53          32  Customer 61     New York
54          67  Customer 64      Houston
55          17  Customer 53      Phoenix
56          43  Customer 69     New York
57          84  Customer 70      Chicago
58          31  Customer 68      Houston
59           9  Customer 25     New York
60          61  Customer 77  Los Angeles
61          87  Customer 28     New York
62          32  Customer 71      Chicago
63          88  Customer 56      Phoenix
64           9  Customer 68      Houston
65          94   Customer 5      Chicago
66          21  Customer 45      Chicago
67          23  Customer 12 Philadelphia
68          28  Customer 17  Los Angeles
69          70  Customer 49      Chicago
70          61  Customer 38  Los Angeles
71          20  Customer 53 Philadelphia
72          15  Customer 27 Philadelphia
73          50  Customer 50      Chicago
74          57  Customer 88 Philadelphia
75          91  Customer 76     New York
76          35  Customer 83      Houston
77          21  Customer 16      Phoenix
78          59  Customer 51  Los Angeles
79          52  Customer 38      Phoenix
80          12  Customer 87      Houston
81          86  Customer 98  Los Angeles
82          69  Customer 98      Chicago
83          65  Customer 11  Los Angeles
84          41  Customer 14      Phoenix
85          49  Customer 25      Houston
86          28   Customer 4 Philadelphia
87           3  Customer 37 Philadelphia
88          96  Customer 42      Chicago
89          61  Customer 18     New York
90          12  Customer 11      Chicago
91          54  Customer 32      Chicago
92           6  Customer 55     New York
93          36  Customer 74      Chicago
94          85  Customer 17      Chicago
95          51  Customer 14      Phoenix
96          90  Customer 81     New York
97           3  Customer 70  Los Angeles
98          46  Customer 68      Chicago
99          54  Customer 55      Chicago
100         66  Customer 65      Phoenix
101          9  Customer 43      Chicago
102         38  Customer 46 Philadelphia
103         41 Customer 100      Phoenix
104         52  Customer 29      Phoenix
105         81  Customer 53 Philadelphia
106         85  Customer 49      Chicago
107         85  Customer 61 Philadelphia
108         41  Customer 95 Philadelphia
109         60  Customer 64      Chicago
110         51  Customer 59      Chicago
111         53  Customer 44     New York
112         99   Customer 9      Houston
113         98  Customer 42      Houston
114          3  Customer 26 Philadelphia
115         20  Customer 80      Phoenix
116         22  Customer 31     New York
117         88  Customer 91     New York
118         43  Customer 53 Philadelphia
119         49  Customer 53  Los Angeles
120         29  Customer 22  Los Angeles
121         76  Customer 63      Houston
122         35  Customer 74     New York
123         87  Customer 87      Chicago
124         78  Customer 69      Phoenix
125         57  Customer 49  Los Angeles
126         31  Customer 10      Chicago
127         54  Customer 77      Phoenix
128         39  Customer 57     New York
129         88  Customer 54  Los Angeles
130         40  Customer 97  Los Angeles
131         98  Customer 70      Houston
132         80  Customer 44  Los Angeles
133         65  Customer 99 Philadelphia
134         22  Customer 49     New York
135         14  Customer 98      Houston
136         99  Customer 20      Phoenix
137         14   Customer 2 Philadelphia
138         59  Customer 24 Philadelphia
139         67  Customer 82  Los Angeles
140         70  Customer 10      Houston
141         45  Customer 32     New York
142         75  Customer 76     New York
143         91  Customer 66      Chicago
144         93   Customer 5 Philadelphia
145         11  Customer 96 Philadelphia
146         66  Customer 91      Houston
147         60  Customer 78      Phoenix
148         76  Customer 75     New York
149         57  Customer 92 Philadelphia
150         64  Customer 60     New York
151         88  Customer 96      Chicago
152         24  Customer 83 Philadelphia
153         97  Customer 13      Houston
154         18  Customer 81      Phoenix
155         21  Customer 93  Los Angeles
156         86  Customer 59      Chicago
157         83  Customer 46     New York
158         66  Customer 83  Los Angeles
159         81  Customer 25      Houston
160         55  Customer 56      Chicago
161         63  Customer 81      Phoenix
162         68  Customer 78     New York
163         74  Customer 20     New York
164         43  Customer 37      Phoenix
165         14  Customer 31     New York
166         78   Customer 6  Los Angeles
167         26  Customer 76      Houston
168         11  Customer 90     New York
169         89  Customer 91      Chicago
170         95  Customer 15 Philadelphia
171         31  Customer 75  Los Angeles
172         31  Customer 90      Chicago
173         43  Customer 71      Houston
174        100  Customer 38      Houston
175         89  Customer 88     New York
176         31  Customer 91     New York
177         87  Customer 87 Philadelphia
178         42   Customer 3     New York
179         14  Customer 47  Los Angeles
180         50  Customer 18 Philadelphia
181         17  Customer 12      Chicago
182         70  Customer 49      Phoenix
183          5   Customer 4 Philadelphia
184         83  Customer 18  Los Angeles
185         43  Customer 21      Phoenix
186         76  Customer 87 Philadelphia
187         64  Customer 79      Phoenix
188         35  Customer 87      Phoenix
189         15  Customer 89 Philadelphia
190         56  Customer 14     New York
191        100  Customer 53      Phoenix
192         86  Customer 67 Philadelphia
193         77  Customer 23 Philadelphia
194         78  Customer 15      Chicago
195         70  Customer 37     New York
196         11  Customer 70      Chicago
197         30  Customer 39      Houston
198         67  Customer 61      Chicago
199          9   Customer 8      Phoenix
200         15  Customer 75      Houston
201          7  Customer 87 Philadelphia
202          4  Customer 17 Philadelphia
203         32  Customer 28      Phoenix
204         12  Customer 63  Los Angeles
205         89  Customer 87      Phoenix
206         96  Customer 17      Houston
207         79  Customer 69 Philadelphia
208         30  Customer 74      Phoenix
209         27  Customer 18 Philadelphia
210          8  Customer 59      Houston
211         27  Customer 52 Philadelphia
212         79  Customer 87  Los Angeles
213         70  Customer 92      Phoenix
214         49  Customer 21      Houston
215         51  Customer 76      Houston
216         33  Customer 66      Houston
217         85  Customer 53 Philadelphia
218         24  Customer 39      Houston
219         23  Customer 24      Phoenix
220         78   Customer 9 Philadelphia
221         24  Customer 54     New York
222         62  Customer 25      Chicago
223         41  Customer 73      Houston
224         31  Customer 24 Philadelphia
225          3  Customer 15     New York
226         85  Customer 23      Phoenix
227         20  Customer 18  Los Angeles
228         28  Customer 94      Houston
229         37   Customer 9     New York
230          5  Customer 92     New York
231         16  Customer 90  Los Angeles
232         91  Customer 11     New York
233         23  Customer 47     New York
234         96  Customer 91      Chicago
235         94  Customer 12      Phoenix
236          6  Customer 29  Los Angeles
237         62  Customer 54      Houston
238          7  Customer 39      Chicago
239         79  Customer 10      Houston
240         62 Customer 100      Chicago
241         18  Customer 85 Philadelphia
242         41   Customer 6     New York
243         46  Customer 85  Los Angeles
244         79  Customer 49      Chicago
245          3  Customer 97     New York
246         51  Customer 11      Chicago
247          7  Customer 37      Phoenix
248         98  Customer 23  Los Angeles
249         95  Customer 94      Phoenix
250          1  Customer 83      Houston
251         70  Customer 69      Phoenix
252         64  Customer 15     New York
253         30  Customer 90      Houston
254         67  Customer 99      Houston
255         78  Customer 64      Houston
256         51  Customer 58  Los Angeles
257          5  Customer 45      Houston
258         43  Customer 98 Philadelphia
259         23  Customer 16 Philadelphia
260         56  Customer 54 Philadelphia
261         27  Customer 80      Phoenix
262          4  Customer 35 Philadelphia
263         69  Customer 14 Philadelphia
264         76  Customer 54      Houston
265         79  Customer 92 Philadelphia
266         33  Customer 98 Philadelphia
267         90  Customer 44  Los Angeles
268         71  Customer 81      Chicago
269         88  Customer 72  Los Angeles
270         84  Customer 90  Los Angeles
271         89  Customer 43      Phoenix
272         20  Customer 23      Chicago
273         81  Customer 72     New York
274         91   Customer 1      Houston
275        100  Customer 83 Philadelphia
276         35  Customer 68      Houston
277         48  Customer 52      Phoenix
278         73  Customer 47     New York
279         93  Customer 91      Chicago
280         17  Customer 77  Los Angeles
281          7  Customer 18      Houston
282         48  Customer 69      Chicago
283         77  Customer 44      Phoenix
284         82  Customer 48  Los Angeles
285         40  Customer 18      Phoenix
286         34  Customer 21  Los Angeles
287         11  Customer 65  Los Angeles
288         78  Customer 21      Houston
289         16  Customer 27      Phoenix
290         19  Customer 32      Chicago
291          9  Customer 20      Chicago
292         29  Customer 46      Houston
293         73  Customer 65     New York
294          2  Customer 20  Los Angeles
295         40  Customer 30  Los Angeles
296         56  Customer 68      Chicago
297          7  Customer 18      Chicago
298         57  Customer 71     New York
299         36  Customer 16      Phoenix
300         85  Customer 82 Philadelphia
301         23  Customer 33     New York
302        100  Customer 92      Phoenix
303         95  Customer 36      Phoenix
304         28  Customer 18      Houston
305         80  Customer 27      Houston
306         89  Customer 87      Phoenix
307         36  Customer 98 Philadelphia
308          9  Customer 11      Phoenix
309         67  Customer 37      Phoenix
310         60  Customer 43     New York
311         55  Customer 70      Houston
312         10  Customer 22     New York
313         36  Customer 98      Houston
314         73  Customer 33  Los Angeles
315          1  Customer 95 Philadelphia
316         65  Customer 98  Los Angeles
317         73  Customer 11      Chicago
318         27  Customer 32      Houston
319         31  Customer 74      Houston
320         67   Customer 6      Phoenix
321         43  Customer 84      Chicago
322         83  Customer 27  Los Angeles
323         33  Customer 13  Los Angeles
324          6  Customer 69     New York
325         26  Customer 43  Los Angeles
326         43   Customer 2     New York
327         52  Customer 91     New York
328         24  Customer 51     New York
329         20  Customer 66  Los Angeles
330         52  Customer 81      Houston
331         52  Customer 87      Phoenix
332         42  Customer 75      Phoenix
333         54  Customer 54     New York
334         77  Customer 99      Houston
335         64  Customer 88      Chicago
336         82  Customer 46  Los Angeles
337         29  Customer 80  Los Angeles
338         29  Customer 71      Phoenix
339         41  Customer 11     New York
340         54  Customer 60      Houston
341         47  Customer 36      Houston
342         16   Customer 8  Los Angeles
343         68  Customer 27      Houston
344         54  Customer 44      Houston
345         44  Customer 27  Los Angeles
346         64  Customer 46      Houston
347         54  Customer 71      Houston
348         94  Customer 47      Phoenix
349         11   Customer 3  Los Angeles
350          1  Customer 46     New York
351         47   Customer 6     New York
352         92  Customer 59 Philadelphia
353         72  Customer 18      Phoenix
354         74  Customer 65  Los Angeles
355          6   Customer 3      Phoenix
356         92  Customer 67 Philadelphia
357         53  Customer 21     New York
358         15   Customer 2  Los Angeles
359         90  Customer 73 Philadelphia
360         39  Customer 11  Los Angeles
361         52  Customer 40      Phoenix
362         47  Customer 11  Los Angeles
363         69  Customer 14  Los Angeles
364         67  Customer 95      Houston
365         40   Customer 1     New York
366         77  Customer 41 Philadelphia
367         60  Customer 21      Chicago
368         59  Customer 82      Phoenix
369         61  Customer 19      Houston
370         82  Customer 56  Los Angeles
371         50  Customer 44      Chicago
372         29  Customer 72 Philadelphia
373         24   Customer 5  Los Angeles
374         82  Customer 57 Philadelphia
375         51  Customer 64      Chicago
376         81  Customer 45 Philadelphia
377         32  Customer 75      Phoenix
378         53  Customer 83 Philadelphia
379        100   Customer 1      Phoenix
380         70   Customer 1  Los Angeles
381         22  Customer 19 Philadelphia
382         16  Customer 62     New York
383         74  Customer 76  Los Angeles
384         42  Customer 97      Chicago
385         28  Customer 26      Houston
386         72  Customer 13     New York
387         91  Customer 85      Chicago
388         43  Customer 58     New York
389         89   Customer 1     New York
390         91  Customer 48      Phoenix
391         18  Customer 76 Philadelphia
392         67  Customer 50     New York
393         98  Customer 96      Phoenix
394         13  Customer 17      Houston
395         31  Customer 89     New York
396         78  Customer 99      Houston
397         99  Customer 37  Los Angeles
398         29  Customer 26     New York
399         15  Customer 76     New York
400         30  Customer 40      Chicago
401         13  Customer 13 Philadelphia
402         44  Customer 84  Los Angeles
403         12  Customer 47     New York
404         86  Customer 41  Los Angeles
405          6  Customer 94  Los Angeles
406          7  Customer 49      Phoenix
407         30  Customer 29 Philadelphia
408         32  Customer 63     New York
409          1  Customer 32      Chicago
410        100  Customer 33      Houston
411         91   Customer 6     New York
412         49  Customer 79      Phoenix
413         44   Customer 4  Los Angeles
414         12  Customer 95     New York
415         57  Customer 51      Chicago
416         39  Customer 15      Houston
417         70  Customer 97      Phoenix
418         63  Customer 47 Philadelphia
419         39  Customer 84     New York
420         24  Customer 97     New York
421          4  Customer 18     New York
422         68  Customer 39     New York
423         40  Customer 74  Los Angeles
424          4   Customer 3     New York
425         81  Customer 98 Philadelphia
426         86  Customer 25  Los Angeles
427         91  Customer 92      Phoenix
428         73  Customer 53      Phoenix
429         25  Customer 48     New York
430         36  Customer 85  Los Angeles
431         42  Customer 15  Los Angeles
432         62   Customer 4  Los Angeles
433         38  Customer 27      Phoenix
434         93 Customer 100      Phoenix
435         58  Customer 94      Houston
436          4  Customer 11      Phoenix
437         82  Customer 25 Philadelphia
438         15  Customer 58 Philadelphia
439         91  Customer 30      Chicago
440         99  Customer 35     New York
441         75  Customer 92     New York
442         36  Customer 94      Phoenix
443         72  Customer 13  Los Angeles
444         92  Customer 44     New York
445         57  Customer 25 Philadelphia
446         65   Customer 6      Phoenix
447         92  Customer 96 Philadelphia
448          5  Customer 74      Houston
449         13  Customer 99      Chicago
450         69  Customer 51      Chicago
451         18  Customer 20      Houston
452         33  Customer 16      Phoenix
453         66  Customer 56     New York
454         23  Customer 71      Phoenix
455          3  Customer 67      Phoenix
456         81  Customer 40 Philadelphia
457         30  Customer 54      Chicago
458         63  Customer 92      Houston
459         95  Customer 32      Chicago
460         73  Customer 40  Los Angeles
461         74   Customer 4      Chicago
462         73  Customer 15      Phoenix
463         30  Customer 45      Houston
464         84  Customer 83 Philadelphia
465         50  Customer 69      Houston
466         70  Customer 94     New York
467         38   Customer 4  Los Angeles
468         32  Customer 47  Los Angeles
469         85  Customer 31  Los Angeles
470         26  Customer 92      Phoenix
471         20  Customer 51     New York
472         35  Customer 23  Los Angeles
473         76  Customer 29     New York
474        100  Customer 94      Chicago
475         95  Customer 63  Los Angeles
476          3  Customer 43      Chicago
477         72  Customer 50     New York
478         84  Customer 24      Houston
479         83  Customer 10      Houston
480         70  Customer 30      Houston
481         67  Customer 87 Philadelphia
482         95  Customer 39      Chicago
483         94  Customer 60      Phoenix
484         50  Customer 85      Houston
485         73  Customer 57 Philadelphia

  CustomerID CustomerName CustomerCity
1 81         Customer 39  Chicago
2 13         Customer 63  Philadelphia
3 18         Customer 98  Chicago
4 76         Customer 39  Houston
5 86         Customer 45  New York

In [15]:
# Task 2.3: Pattern-Based Selection

# Create 'date_columns' with columns starting with "Date" or "Time"
date_columns <- transactions %>%
  select(starts_with("Date"), starts_with("Time"))  # selects columns starting with "Date" or "Time"
print("Selected Date/Time Columns:")
print(date_columns)

# Create 'amount_columns' with columns containing the word "Amount"
amount_columns <- transactions %>%
  select(contains("Amount"))     
print("Selected Columns Containing 'Amount':")
print(amount_columns)        


# Display column names for verification
cat("Date/Time columns:", names(date_columns), "\n")
cat("Amount columns:", names(amount_columns), "\n")

[1] "Selected Date/Time Columns:"
data frame with 0 columns and 500 rows
[1] "Selected Columns Containing 'Amount':"
    TotalAmount
1        632.39
2        114.28
3       1289.24
4        885.40
5         95.95
6       1126.34
7         78.71
8        871.93
9       1347.56
10       633.51
11       572.43
12      1208.43
13      1337.94
14        32.29
15       602.79
16      1476.49
17       520.91
18      1012.57
19       834.08
20      1176.07
21       259.44
22      1424.99
23       897.63
24      1168.05
25       999.24
26       504.96
27        88.45
28       703.88
29      1392.13
30       294.82
31      1219.37
32      1416.35
33        82.98
34       887.44
35       536.69
36       871.96
37      1080.28
38        42.27
39        50.25
40       744.85
41       247.98
42      1158.09
43       817.22
44      1136.57
45      1206.70
46       229.81
47        57.22
48       935.30
49      1220.59
50       808.93
51      1397.43
52      1246.39
53       502.72
54       475.40
55       962.80
56       124.82
57       487.41
58       952.01
59       941.02
60       597.96
61      1491.96
62      1424.38
63       216.52
64       913.13
65       781.85
66       960.77
67       304.06
68       140.76
69      1370.57
70      1150.96
71      1411.95
72       162.98
73       906.83
74       875.19
75       378.17
76       963.57
77       329.58
78      1124.15
79       178.22
80      1184.65
81        96.83
82       570.82
83       144.20
84      1471.59
85       420.46
86       722.72
87       191.97
88       695.21
89       973.31
90       931.78
91       721.24
92      1099.52
93       676.93
94       521.86
95      1349.26
96       721.25
97        68.81
98       789.00
99       129.02
100     1375.08
101      507.05
102      312.95
103      486.77
104     1428.17
105      562.58
106      216.81
107      565.04
108       91.71
109     1016.07
110      537.87
111      431.35
112      316.79
113      443.01
114      445.93
115      768.14
116      133.85
117      268.52
118     1064.21
119     1043.34
120      681.53
121      847.13
122     1414.89
123      292.25
124     1144.26
125     1075.51
126      179.96
127     1208.75
128     1031.13
129     1231.83
130      103.93
131      869.20
132      649.12
133     1326.27
134      887.40
135      641.43
136     1487.44
137      463.25
138     1274.62
139     1154.62
140      488.05
141      965.32
142     1442.78
143      688.87
144     1368.21
145      289.58
146      361.78
147     1001.65
148     1192.22
149      253.81
150     1499.52
151      827.63
152     1109.74
153     1169.26
154     1491.62
155      491.01
156      493.53
157      134.15
158     1280.20
159      491.87
160      163.68
161      299.82
162      414.51
163      770.42
164     1118.96
165      499.81
166      696.28
167      997.09
168      625.59
169     1322.63
170     1365.47
171      242.68
172     1220.70
173     1064.89
174      713.34
175      587.96
176      162.68
177      425.44
178     1345.51
179      927.99
180     1316.78
181      314.66
182      453.17
183      616.11
184     1374.15
185      726.74
186      569.47
187     1488.95
188      782.31
189     1176.03
190      180.03
191      628.76
192      462.32
193      490.24
194      245.20
195      869.66
196     1428.35
197      571.85
198     1126.44
199      322.00
200      867.61
201      979.23
202     1154.91
203     1011.00
204      446.82
205      644.95
206      525.91
207      904.49
208       81.27
209      551.16
210      890.11
211      391.17
212     1437.43
213      866.79
214      514.75
215      847.22
216      493.89
217     1393.51
218      957.29
219      235.06
220      820.90
221      424.71
222      623.34
223      529.65
224      116.06
225     1133.73
226      215.33
227      667.50
228      459.68
229     1138.70
230      533.08
231     1445.64
232     1470.30
233      825.83
234     1034.45
235      940.10
236     1024.36
237     1403.78
238      589.71
239      769.09
240      178.55
241      491.55
242      261.12
243     1423.52
244     1453.94
245       82.05
246     1060.51
247      546.49
248     1015.05
249      394.12
250      237.79
251      277.70
252      305.12
253     1153.30
254     1027.15
255      535.79
256      883.89
257     1249.30
258      720.84
259     1333.49
260      521.39
261     1422.31
262      360.99
263      330.42
264     1365.62
265      715.21
266     1376.67
267      216.36
268     1105.76
269      238.90
270      406.06
271     1070.57
272      895.48
273      304.54
274     1132.28
275       36.37
276      314.71
277     1286.07
278     1270.57
279      654.35
280       77.02
281     1295.11
282       37.33
283      728.18
284     1094.01
285      518.49
286     1380.35
287      695.28
288      393.37
289      936.96
290      266.67
291     1316.92
292      834.69
293     1284.33
294     1104.69
295      938.98
296       54.92
297     1487.43
298      599.98
299      708.66
300      664.62
301      206.62
302      238.82
303      992.51
304      502.01
305      583.86
306      184.44
307      116.39
308      726.38
309      792.50
310      323.46
311      996.67
312     1364.74
313      803.93
314      798.78
315       27.66
316      697.35
317     1407.51
318       64.58
319      411.66
320      435.02
321     1230.65
322      539.52
323      357.76
324      139.91
325       41.59
326      760.69
327     1165.45
328     1349.46
329      619.12
330      469.06
331      286.74
332      361.38
333      179.93
334     1240.02
335     1318.32
336     1220.45
337     1027.87
338      784.41
339      220.97
340     1005.32
341     1469.91
342      318.62
343     1007.80
344     1222.95
345     1446.47
346      916.81
347      910.46
348     1011.00
349      504.76
350      738.02
351      246.96
352      313.01
353      469.41
354      478.25
355     1228.42
356       84.31
357      676.41
358      808.13
359     1082.86
360       84.03
361     1038.23
362     1170.46
363      765.57
364      739.94
365     1004.78
366     1246.05
367     1294.14
368     1168.35
369     1051.02
370      185.86
371      167.74
372      984.27
373      897.16
374     1076.88
375      986.80
376     1204.99
377      878.24
378     1484.31
379      154.62
380     1075.90
381      192.98
382     1163.50
383      594.66
384     1459.42
385     1183.48
386     1167.23
387      929.88
388     1291.34
389      584.87
390     1211.88
391      861.80
392     1416.41
393     1327.99
394      413.87
395      171.84
396     1146.78
397      633.92
398      404.37
399      462.73
400      396.36
401      937.37
402      712.66
403       69.27
404     1326.42
405      232.78
406       60.21
407      366.07
408     1070.39
409      371.68
410     1100.77
411     1025.02
412      288.41
413      119.46
414      848.47
415      167.33
416       95.61
417      118.64
418     1161.95
419     1055.07
420      670.50
421     1425.00
422      915.05
423      838.98
424      887.00
425     1257.96
426      806.39
427      161.21
428     1433.74
429      761.71
430     1433.31
431      351.05
432     1259.22
433      148.13
434      312.11
435     1277.05
436      521.01
437      450.55
438      264.62
439     1032.76
440      498.09
441      152.75
442      290.43
443      818.87
444      393.96
445      662.13
446     1426.21
447      160.64
448      432.08
449      981.39
450     1340.49
451      972.35
452      722.45
453      300.76
454      554.39
455     1411.17
456      378.96
457     1296.63
458     1223.24
459     1144.37
460      691.52
461      104.27
462       67.87
463      512.48
464       42.53
465      975.72
466      142.28
467     1326.34
468     1456.72
469     1400.34
470     1098.41
471      574.09
472      422.83
473       40.69
474     1284.31
475     1396.56
476      908.84
477       35.01
478     1382.09
479     1473.27
480      527.65
481     1155.99
482      121.22
483     1148.92
484     1313.62
485      442.03
486      347.76
487      519.51
488      850.32
489      536.64
490      709.80
491     1007.09
492      362.38
493     1082.04
494     1368.35
495      915.25
496      865.93
497       90.06
498      700.12
499     1388.73
500      304.36
Date/Time columns:
Amount columns: TotalAmount

In [16]:
# Task 2.4: Exclusion Selection
# Create 'no_ids' without TransactionID and CustomerID columns

no_ids <- transactions %>%
  select(-TransactionID, -CustomerID)       #
print("Selected All Columns Except TransactionID and CustomerID:")
print(no_ids)         


# Display column names for verification
cat("Columns after removing IDs:", names(no_ids), "\n")
cat("Number of columns:", ncol(no_ids), "\n")

[1] "Selected All Columns Except TransactionID and CustomerID:"
    CustomerName CustomerCity     ProductName ProductCategory TotalAmount
1    Customer 39      Chicago   Adidas Jacket        Clothing      632.39
2    Customer 63 Philadelphia      Samsung TV           Music      114.28
3    Customer 98      Chicago   Adidas Jacket       Computers     1289.24
4    Customer 39      Houston     Dell Laptop       Computers      885.40
5    Customer 45     New York      Nike Shoes       Computers       95.95
6     Customer 8 Philadelphia   Adidas Jacket     Electronics     1126.34
7    Customer 83     New York      HP Printer        Clothing       78.71
8    Customer 60      Chicago      Samsung TV           Music      871.93
9    Customer 69      Houston       iPhone 14           Music     1347.56
10   Customer 24      Chicago Sony Headphones           Books      633.51
11   Customer 95 Philadelphia      HP Printer          Movies      572.43
12   Customer 22 Philadelphia   Adidas Jacket     Electronics     1208.43
13   Customer 62      Phoenix     Dell Laptop     Electronics     1337.94
14  Customer 100      Phoenix      Nike Shoes           Books       32.29
15   Customer 52     New York      Nike Shoes        Clothing      602.79
16   Customer 20      Chicago      HP Printer     Electronics     1476.49
17   Customer 38     New York Sony Headphones     Electronics      520.91
18   Customer 15      Phoenix     Dell Laptop           Books     1012.57
19    Customer 1      Phoenix Sony Headphones       Computers      834.08
20   Customer 57      Chicago     Dell Laptop       Computers     1176.07
21    Customer 1      Houston      HP Printer           Music      259.44
22    Customer 4     New York       iPhone 14           Books     1424.99
23   Customer 50      Chicago      HP Printer       Computers      897.63
24   Customer 30      Phoenix      Nike Shoes       Computers     1168.05
25   Customer 17     New York       iPhone 14          Movies      999.24
26    Customer 7 Philadelphia       iPhone 14       Computers      504.96
27   Customer 27 Philadelphia      HP Printer     Electronics       88.45
28   Customer 41  Los Angeles   Adidas Jacket           Music      703.88
29   Customer 23     New York      Samsung TV        Clothing     1392.13
30   Customer 48      Houston      Samsung TV           Books      294.82
31   Customer 30      Chicago   Adidas Jacket        Clothing     1219.37
32   Customer 62      Chicago Sony Headphones     Electronics     1416.35
33   Customer 65 Philadelphia       iPhone 14       Computers       82.98
34   Customer 26      Houston   Adidas Jacket           Music      887.44
35   Customer 47     New York      Samsung TV        Clothing      536.69
36   Customer 82     New York   Adidas Jacket        Clothing      871.96
37   Customer 93      Phoenix      Nike Shoes     Electronics     1080.28
38   Customer 61     New York   Adidas Jacket       Computers       42.27
39   Customer 83  Los Angeles Sony Headphones        Clothing       50.25
40   Customer 73      Houston Sony Headphones        Clothing      744.85
41    Customer 9      Phoenix       iPhone 14        Clothing      247.98
42   Customer 20      Chicago Sony Headphones     Electronics     1158.09
43   Customer 74      Houston Sony Headphones           Books      817.22
44   Customer 42      Chicago       iPhone 14       Computers     1136.57
45   Customer 28 Philadelphia       iPhone 14           Music     1206.70
46   Customer 56      Houston      HP Printer     Electronics      229.81
47   Customer 87      Chicago      HP Printer     Electronics       57.22
48   Customer 18 Philadelphia       iPhone 14        Clothing      935.30
49   Customer 73 Philadelphia     Dell Laptop       Computers     1220.59
50   Customer 83      Chicago      Nike Shoes           Music      808.93
51   Customer 26      Phoenix      HP Printer       Computers     1397.43
52   Customer 33     New York   Adidas Jacket     Electronics     1246.39
53   Customer 61     New York   Adidas Jacket          Movies      502.72
54   Customer 64      Houston      Nike Shoes          Movies      475.40
55   Customer 53      Phoenix Sony Headphones     Electronics      962.80
56   Customer 69     New York   Adidas Jacket       Computers      124.82
57   Customer 70      Chicago      Samsung TV     Electronics      487.41
58   Customer 68      Houston   Adidas Jacket          Movies      952.01
59   Customer 25     New York      Samsung TV           Books      941.02
60   Customer 77  Los Angeles      Nike Shoes        Clothing      597.96
61   Customer 28     New York     Dell Laptop       Computers     1491.96
62   Customer 71      Chicago      Samsung TV     Electronics     1424.38
63   Customer 56      Phoenix   Adidas Jacket       Computers      216.52
64   Customer 68      Houston   Adidas Jacket     Electronics      913.13
65    Customer 5      Chicago      Samsung TV           Music      781.85
66   Customer 45      Chicago   Adidas Jacket        Clothing      960.77
67   Customer 12 Philadelphia     Dell Laptop       Computers      304.06
68   Customer 17  Los Angeles     Dell Laptop       Computers      140.76
69   Customer 49      Chicago      Nike Shoes       Computers     1370.57
70   Customer 38  Los Angeles       iPhone 14       Computers     1150.96
71   Customer 53 Philadelphia     Dell Laptop           Music     1411.95
72   Customer 27 Philadelphia Sony Headphones     Electronics      162.98
73   Customer 50      Chicago Sony Headphones       Computers      906.83
74   Customer 88 Philadelphia      Samsung TV           Books      875.19
75   Customer 76     New York   Adidas Jacket       Computers      378.17
76   Customer 83      Houston       iPhone 14           Books      963.57
77   Customer 16      Phoenix      Samsung TV           Books      329.58
78   Customer 51  Los Angeles       iPhone 14     Electronics     1124.15
79   Customer 38      Phoenix       iPhone 14       Computers      178.22
80   Customer 87      Houston       iPhone 14        Clothing     1184.65
81   Customer 98  Los Angeles     Dell Laptop     Electronics       96.83
82   Customer 98      Chicago   Adidas Jacket           Music      570.82
83   Customer 11  Los Angeles       iPhone 14           Books      144.20
84   Customer 14      Phoenix       iPhone 14       Computers     1471.59
85   Customer 25      Houston      Nike Shoes           Books      420.46
86    Customer 4 Philadelphia   Adidas Jacket        Clothing      722.72
87   Customer 37 Philadelphia     Dell Laptop           Music      191.97
88   Customer 42      Chicago   Adidas Jacket       Computers      695.21
89   Customer 18     New York      HP Printer       Computers      973.31
90   Customer 11      Chicago     Dell Laptop        Clothing      931.78
91   Customer 32      Chicago      HP Printer           Books      721.24
92   Customer 55     New York       iPhone 14          Movies     1099.52
93   Customer 74      Chicago   Adidas Jacket       Computers      676.93
94   Customer 17      Chicago     Dell Laptop     Electronics      521.86
95   Customer 14      Phoenix   Adidas Jacket           Books     1349.26
96   Customer 81     New York      Samsung TV     Electronics      721.25
97   Customer 70  Los Angeles   Adidas Jacket           Music       68.81
98   Customer 68      Chicago      Nike Shoes          Movies      789.00
99   Customer 55      Chicago      Nike Shoes           Music      129.02
100  Customer 65      Phoenix     Dell Laptop           Books     1375.08
101  Customer 43      Chicago      Nike Shoes           Books      507.05
102  Customer 46 Philadelphia Sony Headphones     Electronics      312.95
103 Customer 100      Phoenix Sony Headphones     Electronics      486.77
104  Customer 29      Phoenix     Dell Laptop     Electronics     1428.17
105  Customer 53 Philadelphia       iPhone 14          Movies      562.58
106  Customer 49      Chicago     Dell Laptop     Electronics      216.81
107  Customer 61 Philadelphia   Adidas Jacket          Movies      565.04
108  Customer 95 Philadelphia      HP Printer           Music       91.71
109  Customer 64      Chicago   Adidas Jacket          Movies     1016.07
110  Customer 59      Chicago      Samsung TV        Clothing      537.87
111  Customer 44     New York       iPhone 14           Music      431.35
112   Customer 9      Houston      Nike Shoes       Computers      316.79
113  Customer 42      Houston      HP Printer           Music      443.01
114  Customer 26 Philadelphia      Nike Shoes           Music      445.93
115  Customer 80      Phoenix Sony Headphones           Music      768.14
116  Customer 31     New York       iPhone 14           Music      133.85
117  Customer 91     New York   Adidas Jacket           Books      268.52
118  Customer 53 Philadelphia     Dell Laptop           Music     1064.21
119  Customer 53  Los Angeles      HP Printer       Computers     1043.34
120  Customer 22  Los Angeles      Samsung TV           Books      681.53
121  Customer 63      Houston Sony Headphones           Books      847.13
122  Customer 74     New York   Adidas Jacket           Books     1414.89
123  Customer 87      Chicago   Adidas Jacket       Computers      292.25
124  Customer 69      Phoenix     Dell Laptop           Books     1144.26
125  Customer 49  Los Angeles       iPhone 14           Music     1075.51
126  Customer 10      Chicago     Dell Laptop        Clothing      179.96
127  Customer 77      Phoenix   Adidas Jacket       Computers     1208.75
128  Customer 57     New York   Adidas Jacket           Music     1031.13
129  Customer 54  Los Angeles   Adidas Jacket     Electronics     1231.83
130  Customer 97  Los Angeles     Dell Laptop           Books      103.93
131  Customer 70      Houston   Adidas Jacket          Movies      869.20
132  Customer 44  Los Angeles   Adidas Jacket        Clothing      649.12
133  Customer 99 Philadelphia Sony Headphones     Electronics     1326.27
134  Customer 49     New York      Samsung TV          Movies      887.40
135  Customer 98      Houston      HP Printer     Electronics      641.43
136  Customer 20      Phoenix      HP Printer     Electronics     1487.44
137   Customer 2 Philadelphia      HP Printer     Electronics      463.25
138  Customer 24 Philadelphia Sony Headphones     Electronics     1274.62
139  Customer 82  Los Angeles Sony Headphones     Electronics     1154.62
140  Customer 10      Houston      Samsung TV     Electronics      488.05
141  Customer 32     New York   Adidas Jacket           Books      965.32
142  Customer 76     New York Sony Headphones        Clothing     1442.78
143  Customer 66      Chicago      Samsung TV          Movies      688.87
144   Customer 5 Philadelphia      Samsung TV          Movies     1368.21
145  Customer 96 Philadelphia       iPhone 14     Electronics      289.58
146  Customer 91      Houston       iPhone 14     Electronics      361.78
147  Customer 78      Phoenix      Nike Shoes           Books     1001.65
148  Customer 75     New York       iPhone 14           Books     1192.22
149  Customer 92 Philadelphia     Dell Laptop           Books      253.81
150  Customer 60     New York Sony Headphones     Electronics     1499.52
151  Customer 96      Chicago Sony Headphones        Clothing      827.63
152  Customer 83 Philadelphia      HP Printer           Books     1109.74
153  Customer 13      Houston      Samsung TV        Clothing     1169.26
154  Customer 81      Phoenix Sony Headphones           Books     1491.62
155  Customer 93  Los Angeles      Nike Shoes       Computers      491.01
156  Customer 59      Chicago      Samsung TV          Movies      493.53
157  Customer 46     New York      Nike Shoes        Clothing      134.15
158  Customer 83  Los Angeles   Adidas Jacket     Electronics     1280.20
159  Customer 25      Houston Sony Headphones           Books      491.87
160  Customer 56      Chicago       iPhone 14       Computers      163.68
161  Customer 81      Phoenix      Nike Shoes           Books      299.82
162  Customer 78     New York      Samsung TV           Music      414.51
163  Customer 20     New York      Nike Shoes          Movies      770.42
164  Customer 37      Phoenix      Samsung TV       Computers     1118.96
165  Customer 31     New York     Dell Laptop          Movies      499.81
166   Customer 6  Los Angeles     Dell Laptop          Movies      696.28
167  Customer 76      Houston Sony Headphones       Computers      997.09
168  Customer 90     New York      HP Printer          Movies      625.59
169  Customer 91      Chicago Sony Headphones       Computers     1322.63
170  Customer 15 Philadelphia      Samsung TV           Music     1365.47
171  Customer 75  Los Angeles Sony Headphones       Computers      242.68
172  Customer 90      Chicago     Dell Laptop           Books     1220.70
173  Customer 71      Houston      Nike Shoes           Music     1064.89
174  Customer 38      Houston      HP Printer          Movies      713.34
175  Customer 88     New York      Nike Shoes           Books      587.96
176  Customer 91     New York      HP Printer           Music      162.68
177  Customer 87 Philadelphia Sony Headphones       Computers      425.44
178   Customer 3     New York Sony Headphones           Music     1345.51
179  Customer 47  Los Angeles      HP Printer     Electronics      927.99
180  Customer 18 Philadelphia     Dell Laptop       Computers     1316.78
181  Customer 12      Chicago       iPhone 14       Computers      314.66
182  Customer 49      Phoenix       iPhone 14           Books      453.17
183   Customer 4 Philadelphia      Nike Shoes     Electronics      616.11
184  Customer 18  Los Angeles      HP Printer          Movies     1374.15
185  Customer 21      Phoenix Sony Headphones        Clothing      726.74
186  Customer 87 Philadelphia      Samsung TV       Computers      569.47
187  Customer 79      Phoenix       iPhone 14       Computers     1488.95
188  Customer 87      Phoenix Sony Headphones     Electronics      782.31
189  Customer 89 Philadelphia      Nike Shoes        Clothing     1176.03
190  Customer 14     New York     Dell Laptop        Clothing      180.03
191  Customer 53      Phoenix      HP Printer       Computers      628.76
192  Customer 67 Philadelphia Sony Headphones          Movies      462.32
193  Customer 23 Philadelphia     Dell Laptop           Music      490.24
194  Customer 15      Chicago      Samsung TV           Music      245.20
195  Customer 37     New York   Adidas Jacket           Books      869.66
196  Customer 70      Chicago      Nike Shoes           Books     1428.35
197  Customer 39      Houston     Dell Laptop     Electronics      571.85
198  Customer 61      Chicago   Adidas Jacket          Movies     1126.44
199   Customer 8      Phoenix      Nike Shoes           Music      322.00
200  Customer 75      Houston      Samsung TV           Books      867.61
201  Customer 87 Philadelphia       iPhone 14       Computers      979.23
202  Customer 17 Philadelphia   Adidas Jacket        Clothing     1154.91
203  Customer 28      Phoenix   Adidas Jacket       Computers     1011.00
204  Customer 63  Los Angeles Sony Headphones        Clothing      446.82
205  Customer 87      Phoenix   Adidas Jacket           Books      644.95
206  Customer 17      Houston       iPhone 14          Movies      525.91
207  Customer 69 Philadelphia       iPhone 14     Electronics      904.49
208  Customer 74      Phoenix       iPhone 14          Movies       81.27
209  Customer 18 Philadelphia      HP Printer     Electronics      551.16
210  Customer 59      Houston     Dell Laptop        Clothing      890.11
211  Customer 52 Philadelphia      Samsung TV           Books      391.17
212  Customer 87  Los Angeles     Dell Laptop        Clothing     1437.43
213  Customer 92      Phoenix       iPhone 14       Computers      866.79
214  Customer 21      Houston      Nike Shoes     Electronics      514.75
215  Customer 76      Houston      HP Printer           Books      847.22
216  Customer 66      Houston      Samsung TV       Computers      493.89
217  Customer 53 Philadelphia      HP Printer        Clothing     1393.51
218  Customer 39      Houston     Dell Laptop     Electronics      957.29
219  Customer 24      Phoenix   Adidas Jacket          Movies      235.06
220   Customer 9 Philadelphia      Samsung TV           Books      820.90
221  Customer 54     New York Sony Headphones       Computers      424.71
222  Customer 25      Chicago      Samsung TV        Clothing      623.34
223  Customer 73      Houston Sony Headphones          Movies      529.65
224  Customer 24 Philadelphia      Samsung TV     Electronics      116.06
225  Customer 15     New York Sony Headphones           Music     1133.73
226  Customer 23      Phoenix     Dell Laptop       Computers      215.33
227  Customer 18  Los Angeles   Adidas Jacket          Movies      667.50
228  Customer 94      Houston   Adidas Jacket           Music      459.68
229   Customer 9     New York     Dell Laptop     Electronics     1138.70
230  Customer 92     New York      Samsung TV     Electronics      533.08
231  Customer 90  Los Angeles   Adidas Jacket     Electronics     1445.64
232  Customer 11     New York     Dell Laptop       Computers     1470.30
233  Customer 47     New York   Adidas Jacket     Electronics      825.83
234  Customer 91      Chicago Sony Headphones           Books     1034.45
235  Customer 12      Phoenix      Samsung TV     Electronics      940.10
236  Customer 29  Los Angeles     Dell Laptop           Books     1024.36
237  Customer 54      Houston      HP Printer           Music     1403.78
238  Customer 39      Chicago Sony Headphones           Books      589.71
239  Customer 10      Houston      HP Printer        Clothing      769.09
240 Customer 100      Chicago      HP Printer     Electronics      178.55
241  Customer 85 Philadelphia     Dell Laptop        Clothing      491.55
242   Customer 6     New York Sony Headphones           Books      261.12
243  Customer 85  Los Angeles Sony Headphones        Clothing     1423.52
244  Customer 49      Chicago     Dell Laptop        Clothing     1453.94
245  Customer 97     New York      Nike Shoes       Computers       82.05
246  Customer 11      Chicago   Adidas Jacket          Movies     1060.51
247  Customer 37      Phoenix      HP Printer       Computers      546.49
248  Customer 23  Los Angeles   Adidas Jacket           Books     1015.05
249  Customer 94      Phoenix       iPhone 14           Books      394.12
250  Customer 83      Houston      HP Printer          Movies      237.79
251  Customer 69      Phoenix   Adidas Jacket     Electronics      277.70
252  Customer 15     New York     Dell Laptop           Music      305.12
253  Customer 90      Houston     Dell Laptop           Books     1153.30
254  Customer 99      Houston      HP Printer        Clothing     1027.15
255  Customer 64      Houston     Dell Laptop           Books      535.79
256  Customer 58  Los Angeles     Dell Laptop     Electronics      883.89
257  Customer 45      Houston      HP Printer        Clothing     1249.30
258  Customer 98 Philadelphia       iPhone 14        Clothing      720.84
259  Customer 16 Philadelphia   Adidas Jacket        Clothing     1333.49
260  Customer 54 Philadelphia   Adidas Jacket           Books      521.39
261  Customer 80      Phoenix      HP Printer          Movies     1422.31
262  Customer 35 Philadelphia      Nike Shoes           Books      360.99
263  Customer 14 Philadelphia   Adidas Jacket     Electronics      330.42
264  Customer 54      Houston      Nike Shoes       Computers     1365.62
265  Customer 92 Philadelphia      Samsung TV          Movies      715.21
266  Customer 98 Philadelphia     Dell Laptop           Music     1376.67
267  Customer 44  Los Angeles   Adidas Jacket     Electronics      216.36
268  Customer 81      Chicago      HP Printer           Music     1105.76

## Part 3: Row Filtering with `filter()`

Learn to filter rows based on various conditions.

In [19]:
# Task 3.1: Single Condition Filtering

# Filter transactions with TotalAmount > $100
high_value_transactions <- transactions %>%
  filter(TotalAmount > 100)                
print("Items with TotalAmount > 100:")
print(high_value_transactions)          


# Filter transactions from "Electronics" category
electronics_transactions <- transactions %>%
  filter(ProductCategory == "Electronics")
print("Items in Electronics Category:")
print(electronics_transactions)


# Display results
cat("High value transactions (>$100):", nrow(high_value_transactions), "rows\n")
cat("Electronics transactions:", nrow(electronics_transactions), "rows\n")

[1] "Items with TotalAmount > 100:"
    TransactionID CustomerID CustomerName CustomerCity     ProductName
1               1         81  Customer 39      Chicago   Adidas Jacket
2               2         13  Customer 63 Philadelphia      Samsung TV
3               3         18  Customer 98      Chicago   Adidas Jacket
4               4         76  Customer 39      Houston     Dell Laptop
5               6         37   Customer 8 Philadelphia   Adidas Jacket
6               8         11  Customer 60      Chicago      Samsung TV
7               9         13  Customer 69      Houston       iPhone 14
8              10         55  Customer 24      Chicago Sony Headphones
9              11        100  Customer 95 Philadelphia      HP Printer
10             12         89  Customer 22 Philadelphia   Adidas Jacket
11             13         56  Customer 62      Phoenix     Dell Laptop
12             15          1  Customer 52     New York      Nike Shoes
13             16         78  Customer 20      Chicago      HP Printer
14             17          2  Customer 38     New York Sony Headphones
15             18          5  Customer 15      Phoenix     Dell Laptop
16             19          7   Customer 1      Phoenix Sony Headphones
17             20         27  Customer 57      Chicago     Dell Laptop
18             21         31   Customer 1      Houston      HP Printer
19             22         80   Customer 4     New York       iPhone 14
20             23         57  Customer 50      Chicago      HP Printer
21             24         88  Customer 30      Phoenix      Nike Shoes
22             25         97  Customer 17     New York       iPhone 14
23             26         34   Customer 7 Philadelphia       iPhone 14
24             28         54  Customer 41  Los Angeles   Adidas Jacket
25             29          3  Customer 23     New York      Samsung TV
26             30         98  Customer 48      Houston      Samsung TV
27             31         11  Customer 30      Chicago   Adidas Jacket
28             32         21  Customer 62      Chicago Sony Headphones
29             34         62  Customer 26      Houston   Adidas Jacket
30             35         24  Customer 47     New York      Samsung TV
31             36         47  Customer 82     New York   Adidas Jacket
32             37         66  Customer 93      Phoenix      Nike Shoes
33             40         30  Customer 73      Houston Sony Headphones
34             41         60   Customer 9      Phoenix       iPhone 14
35             42         59  Customer 20      Chicago Sony Headphones
36             43         27  Customer 74      Houston Sony Headphones
37             44          7  Customer 42      Chicago       iPhone 14
38             45          1  Customer 28 Philadelphia       iPhone 14
39             46         40  Customer 56      Houston      HP Printer
40             48         71  Customer 18 Philadelphia       iPhone 14
41             49         17  Customer 73 Philadelphia     Dell Laptop
42             50         92  Customer 83      Chicago      Nike Shoes
43             51         20  Customer 26      Phoenix      HP Printer
44             52         31  Customer 33     New York   Adidas Jacket
45             53         32  Customer 61     New York   Adidas Jacket
46             54         67  Customer 64      Houston      Nike Shoes
47             55         17  Customer 53      Phoenix Sony Headphones
48             56         43  Customer 69     New York   Adidas Jacket
49             57         84  Customer 70      Chicago      Samsung TV
50             58         31  Customer 68      Houston   Adidas Jacket
51             59          9  Customer 25     New York      Samsung TV
52             60         61  Customer 77  Los Angeles      Nike Shoes
53             61         87  Customer 28     New York     Dell Laptop
54             62         32  Customer 71      Chicago      Samsung TV
55             63         88  Customer 56      Phoenix   Adidas Jacket
56             64          9  Customer 68      Houston   Adidas Jacket
57             65         94   Customer 5      Chicago      Samsung TV
58             66         21  Customer 45      Chicago   Adidas Jacket
59             67         23  Customer 12 Philadelphia     Dell Laptop
60             68         28  Customer 17  Los Angeles     Dell Laptop
61             69         70  Customer 49      Chicago      Nike Shoes
62             70         61  Customer 38  Los Angeles       iPhone 14
63             71         20  Customer 53 Philadelphia     Dell Laptop
64             72         15  Customer 27 Philadelphia Sony Headphones
65             73         50  Customer 50      Chicago Sony Headphones
66             74         57  Customer 88 Philadelphia      Samsung TV
67             75         91  Customer 76     New York   Adidas Jacket
68             76         35  Customer 83      Houston       iPhone 14
69             77         21  Customer 16      Phoenix      Samsung TV
70             78         59  Customer 51  Los Angeles       iPhone 14
71             79         52  Customer 38      Phoenix       iPhone 14
72             80         12  Customer 87      Houston       iPhone 14
73             82         69  Customer 98      Chicago   Adidas Jacket
74             83         65  Customer 11  Los Angeles       iPhone 14
75             84         41  Customer 14      Phoenix       iPhone 14
76             85         49  Customer 25      Houston      Nike Shoes
77             86         28   Customer 4 Philadelphia   Adidas Jacket
78             87          3  Customer 37 Philadelphia     Dell Laptop
79             88         96  Customer 42      Chicago   Adidas Jacket
80             89         61  Customer 18     New York      HP Printer
81             90         12  Customer 11      Chicago     Dell Laptop
82             91         54  Customer 32      Chicago      HP Printer
83             92          6  Customer 55     New York       iPhone 14
84             93         36  Customer 74      Chicago   Adidas Jacket
85             94         85  Customer 17      Chicago     Dell Laptop
86             95         51  Customer 14      Phoenix   Adidas Jacket
87             96         90  Customer 81     New York      Samsung TV
88             98         46  Customer 68      Chicago      Nike Shoes
89             99         54  Customer 55      Chicago      Nike Shoes
90            100         66  Customer 65      Phoenix     Dell Laptop
91            101          9  Customer 43      Chicago      Nike Shoes
92            102         38  Customer 46 Philadelphia Sony Headphones
93            103         41 Customer 100      Phoenix Sony Headphones
94            104         52  Customer 29      Phoenix     Dell Laptop
95            105         81  Customer 53 Philadelphia       iPhone 14
96            106         85  Customer 49      Chicago     Dell Laptop
97            107         85  Customer 61 Philadelphia   Adidas Jacket
98            109         60  Customer 64      Chicago   Adidas Jacket
99            110         51  Customer 59      Chicago      Samsung TV
100           111         53  Customer 44     New York       iPhone 14
101           112         99   Customer 9      Houston      Nike Shoes
102           113         98  Customer 42      Houston      HP Printer
103           114          3  Customer 26 Philadelphia      Nike Shoes
104           115         20  Customer 80      Phoenix Sony Headphones
105           116         22  Customer 31     New York       iPhone 14
106           117         88  Customer 91     New York   Adidas Jacket
107           118         43  Customer 53 Philadelphia     Dell Laptop
108           119         49  Customer 53  Los Angeles      HP Printer
109           120         29  Customer 22  Los Angeles      Samsung TV
110           121         76  Customer 63      Houston Sony Headphones
111           122         35  Customer 74     New York   Adidas Jacket
112           123         87  Customer 87      Chicago   Adidas Jacket
113           124         78  Customer 69      Phoenix     Dell Laptop
114           125         57  Customer 49  Los Angeles       iPhone 14
115           126         31  Customer 10      Chicago     Dell Laptop
116           127         54  Customer 77      Phoenix   Adidas Jacket
117           128         39  Customer 57     New York   Adidas Jacket
118           129         88  Customer 54  Los Angeles   Adidas Jacket
119           130         40  Customer 97  Los Angeles     Dell Laptop
120           131         98  Customer 70      Houston   Adidas Jacket
121           132         80  Customer 44  Los Angeles   Adidas Jacket
122           133         65  Customer 99 Philadelphia Sony Headphones
123           134         22  Customer 49     New York      Samsung TV
124           135         14  Customer 98      Houston      HP Printer
125           136         99  Customer 20      Phoenix      HP Printer
126           137         14   Customer 2 Philadelphia      HP Printer
127           138         59  Customer 24 Philadelphia Sony Headphones
128           139         67  Customer 82  Los Angeles Sony Headphones
129           140         70  Customer 10      Houston      Samsung TV
130           141         45  Customer 32     New York   Adidas Jacket
131           142         75  Customer 76     New York Sony Headphones
132           143         91  Customer 66      Chicago      Samsung TV
133           144         93   Customer 5 Philadelphia      Samsung TV
134           145         11  Customer 96 Philadelphia       iPhone 14
135           146         66  Customer 91      Houston       iPhone 14
136           147         60  Customer 78      Phoenix      Nike Shoes
137           148         76  Customer 75     New York       iPhone 14
138           149         57  Customer 92 Philadelphia     Dell Laptop
139           150         64  Customer 60     New York Sony Headphones
140           151         88  Customer 96      Chicago Sony Headphones
141           152         24  Customer 83 Philadelphia      HP Printer
142           153         97  Customer 13      Houston      Samsung TV
143           154         18  Customer 81      Phoenix Sony Headphones
144           155         21  Customer 93  Los Angeles      Nike Shoes
145           156         86  Customer 59      Chicago      Samsung TV
146           157         83  Customer 46     New York      Nike Shoes
147           158         66  Customer 83  Los Angeles   Adidas Jacket
148           159         81  Customer 25      Houston Sony Headphones
149           160         55  Customer 56      Chicago       iPhone 14
150           161         63  Customer 81      Phoenix      Nike Shoes
151           162         68  Customer 78     New York      Samsung TV
152           163         74  Customer 20     New York      Nike Shoes
153           164         43  Customer 37      Phoenix      Samsung TV
154           165         14  Customer 31     New York     Dell Laptop
155           166         78   Customer 6  Los Angeles     Dell Laptop
156           167         26  Customer 76      Houston Sony Headphones
157           168         11  Customer 90     New York      HP Printer
158           169         89  Customer 91      Chicago Sony Headphones
159           170         95  Customer 15 Philadelphia      Samsung TV
160           171         31  Customer 75  Los Angeles Sony Headphones
161           172         31  Customer 90      Chicago     Dell Laptop
162           173         43  Customer 71      Houston      Nike Shoes
163           174        100  Customer 38      Houston      HP Printer
164           175         89  Customer 88     New York      Nike Shoes
165           176         31  Customer 91     New York      HP Printer
166           177         87  Customer 87 Philadelphia Sony Headphones
167           178         42   Customer 3     New York Sony Headphones
168           179         14  Customer 47  Los Angeles      HP Printer
169           180         50  Customer 18 Philadelphia     Dell Laptop
170           181         17  Customer 12      Chicago       iPhone 14
171           182         70  Customer 49      Phoenix       iPhone 14
172           183          5   Customer 4 Philadelphia      Nike Shoes
173           184         83  Customer 18  Los Angeles      HP Printer
174           185         43  Customer 21      Phoenix Sony Headphones
175           186         76  Customer 87 Philadelphia      Samsung TV
176           187         64  Customer 79      Phoenix       iPhone 14
177           188         35  Customer 87      Phoenix Sony Headphones
178           189         15  Customer 89 Philadelphia      Nike Shoes
179           190         56  Customer 14     New York     Dell Laptop
180           191        100  Customer 53      Phoenix      HP Printer
181           192         86  Customer 67 Philadelphia Sony Headphones
182           193         77  Customer 23 Philadelphia     Dell Laptop
183           194         78  Customer 15      Chicago      Samsung TV
184           195         70  Customer 37     New York   Adidas Jacket
185           196         11  Customer 70      Chicago      Nike Shoes
186           197         30  Customer 39      Houston     Dell Laptop
187           198         67  Customer 61      Chicago   Adidas Jacket
188           199          9   Customer 8      Phoenix      Nike Shoes
189           200         15  Customer 75      Houston      Samsung TV
190           201          7  Customer 87 Philadelphia       iPhone 14
191           202          4  Customer 17 Philadelphia   Adidas Jacket
192           203         32  Customer 28      Phoenix   Adidas Jacket
193           204         12  Customer 63  Los Angeles Sony Headphones
194           205         89  Customer 87      Phoenix   Adidas Jacket
195           206         96  Customer 17      Houston       iPhone 14
196           207         79  Customer 69 Philadelphia       iPhone 14
197           209         27  Customer 18 Philadelphia      HP Printer
198           210          8  Customer 59      Houston     Dell Laptop
199           211         27  Customer 52 Philadelphia      Samsung TV
200           212         79  Customer 87  Los Angeles     Dell Laptop
201           213         70  Customer 92      Phoenix       iPhone 14
202           214         49  Customer 21      Houston      Nike Shoes
203           215         51  Customer 76      Houston      HP Printer
204           216         33  Customer 66      Houston      Samsung TV
205           217         85  Customer 53 Philadelphia      HP Printer
206           218         24  Customer 39      Houston     Dell Laptop
207           219         23  Customer 24      Phoenix   Adidas Jacket
208           220         78   Customer 9 Philadelphia      Samsung TV
209           221         24  Customer 54     New York Sony Headphones
210           222         62  Customer 25      Chicago      Samsung TV
211           223         41  Customer 73      Houston Sony Headphones
212           224         31  Customer 24 Philadelphia      Samsung TV
213           225          3  Customer 15     New York Sony Headphones
214           226         85  Customer 23      Phoenix     Dell Laptop
215           227         20  Customer 18  Los Angeles   Adidas Jacket
216           228         28  Customer 94      Houston   Adidas Jacket
217           229         37   Customer 9     New York     Dell Laptop
218           230          5  Customer 92     New York      Samsung TV
219           231         16  Customer 90  Los Angeles   Adidas Jacket
220           232         91  Customer 11     New York     Dell Laptop
221           233         23  Customer 47     New York   Adidas Jacket
222           234         96  Customer 91      Chicago Sony Headphones
223           235         94  Customer 12      Phoenix      Samsung TV
224           236          6  Customer 29  Los Angeles     Dell Laptop
225           237         62  Customer 54      Houston      HP Printer
226           238          7  Customer 39      Chicago Sony Headphones
227           239         79  Customer 10      Houston      HP Printer
228           240         62 Customer 100      Chicago      HP Printer
229           241         18  Customer 85 Philadelphia     Dell Laptop
230           242         41   Customer 6     New York Sony Headphones
231           243         46  Customer 85  Los Angeles Sony Headphones
232           244         79  Customer 49      Chicago     Dell Laptop
233           246         51  Customer 11      Chicago   Adidas Jacket
234           247          7  Customer 37      Phoenix      HP Printer
235           248         98  Customer 23  Los Angeles   Adidas Jacket
236           249         95  Customer 94      Phoenix       iPhone 14
237           250          1  Customer 83      Houston      HP Printer
238           251         70  Customer 69      Phoenix   Adidas Jacket
239           252         64  Customer 15     New York     Dell Laptop
240           253         30  Customer 90      Houston     Dell Laptop
241           254         67  Customer 99      Houston      HP Printer
242           255         78  Customer 64      Houston     Dell Laptop
243           256         51  Customer 58  Los Angeles     Dell Laptop
244           257          5  Customer 45      Houston      HP Printer
245           258         43  Customer 98 Philadelphia       iPhone 14
246           259         23  Customer 16 Philadelphia   Adidas Jacket
247           260         56  Customer 54 Philadelphia   Adidas Jacket
248           261         27  Customer 80      Phoenix      HP Printer
249           262          4  Customer 35 Philadelphia      Nike Shoes
250           263         69  Customer 14 Philadelphia   Adidas Jacket
251           264         76  Customer 54      Houston      Nike Shoes
252           265         79  Customer 92 Philadelphia      Samsung TV
253           266         33  Customer 98 Philadelphia     Dell Laptop
254           267         90  Customer 44  Los Angeles   Adidas Jacket
255           268         71  Customer 81      Chicago      HP Printer
256           269         88  Customer 72  Los Angeles      Nike Shoes
257           270         84  Customer 90  Los Angeles   Adidas Jacket
258           271         89  Customer 43      Phoenix      HP Printer
259           272         20  Customer 23      Chicago      HP Printer
260           273         81  Customer 72     New York Sony Headphones
261           274         91   Customer 1      Houston   Adidas Jacket
262           276         35  Customer 68      Houston   Adidas Jacket
263           277         48  Customer 52      Phoenix      HP Printer
264           278         73  Customer 47     New York      Samsung TV
265           279         93  Customer 91      Chicago      Samsung TV
266           281          7  Customer 18      Houston Sony Headphones
267           283         77  Customer 44      Phoenix      Samsung TV
268           284         82  Customer 48  Los Angeles      Nike Shoes
269           285         40  Customer 18      Phoenix      HP Printer
270           286         34  Customer 21  Los Angeles      Nike Shoes
271           287         11  Customer 65  Los Angeles      Samsung TV
272           288         78  Customer 21      Houston       iPhone 14
273           289         16  Customer 27      Phoenix      Samsung TV
274           290         19  Customer 32      Chicago       iPhone 14
275           291          9  Customer 20      Chicago   Adidas Jacket
276           292         29  Customer 46      Houston      HP Printer
277           293         73  Customer 65     New York       iPhone 14
278           294          2  Customer 20  Los Angeles      Nike Shoes
279           295         40  Customer 30  Los Angeles      Nike Shoes
280           297          7  Customer 18      Chicago       iPhone 14

In [20]:
# Task 3.2: Multiple Condition Filtering (AND)
# Filter for TotalAmount > $50 AND Quantity > 1 AND CustomerCity == "New York"

ny_bulk_purchases <- transactions %>%
  filter(TotalAmount > 50, Quantity > 1, CustomerCity == "New York")


# Display results
cat("NY bulk purchases:", nrow(ny_bulk_purchases), "rows\n")
if(nrow(ny_bulk_purchases) > 0) {
  head(ny_bulk_purchases)
}

NY bulk purchases: 75 rows

  TransactionID CustomerID CustomerName CustomerCity ProductName
1  5            86         Customer 45  New York     Nike Shoes
2  7            45         Customer 83  New York     HP Printer
3 15             1         Customer 52  New York     Nike Shoes
4 22            80         Customer 4   New York     iPhone 14
5 25            97         Customer 17  New York     iPhone 14
6 29             3         Customer 23  New York     Samsung TV
  ProductCategory TotalAmount Quantity TransactionDate
1 Computers         95.95     5        2024-08-13
2 Clothing          78.71     3        2024-05-02
3 Clothing         602.79     5        2024-01-05
4 Books           1424.99     7        2024-02-01
5 Movies           999.24     2        2024-02-03
6 Clothing        1392.13     5        2024-04-30

In [21]:
# Task 3.3: Multiple Condition Filtering (OR)
# Filter for ProductCategory = "Books" OR "Music" OR "Movies"

entertainment_transactions <- transactions %>%
  filter(ProductCategory %in% c("Books", "Music", "Movies"))


# Display results
cat("Entertainment transactions:", nrow(entertainment_transactions), "rows\n")
if(nrow(entertainment_transactions) > 0) {
  head(entertainment_transactions)
}

Entertainment transactions: 227 rows

  TransactionID CustomerID CustomerName CustomerCity ProductName
1  2             13        Customer 63  Philadelphia Samsung TV
2  8             11        Customer 60  Chicago      Samsung TV
3  9             13        Customer 69  Houston      iPhone 14
4 10             55        Customer 24  Chicago      Sony Headphones
5 11            100        Customer 95  Philadelphia HP Printer
6 14             19        Customer 100 Phoenix      Nike Shoes
  ProductCategory TotalAmount Quantity TransactionDate
1 Music            114.28     3        2024-12-08
2 Music            871.93     3        2024-04-30
3 Music           1347.56     8        2024-08-08
4 Books            633.51     1        2024-06-23
5 Movies           572.43     6        2024-12-09
6 Books             32.29     3        2024-12-11

In [ ]:
# Task 3.4: Date-Based Filtering
# Filter transactions from March 2024
# Note: Adjust the date format and column name based on your actual data

march_transactions <- transactions %>%
  # Your code here (you may need to convert date format first):
  filter(TransactionDate >= as.Date("2024-03-01") & TransactionDate <= as.Date("2024-03-31"))



# Display results
cat("March 2024 transactions:", nrow(march_transactions), "rows\n")

March 2024 transactions: 41 rows

In [23]:
# Task 3.5: Advanced Filtering Challenge
# Find customers who made purchases in both "Electronics" AND "Clothing" categories
# Hint: This requires identifying customers who appear in both categories

# Step 1: Find customers who bought Electronics
electronics_customers <- transactions %>%
  filter(ProductCategory == "Electronics")


# Step 2: Find customers who bought Clothing
clothing_customers <- transactions %>%
  filter(ProductCategory == "Clothing")


# Step 3: Find customers who bought both
both_categories_customers <- transactions %>%
  filter(CustomerID %in% electronics_customers$CustomerID & 
         CustomerID %in% clothing_customers$CustomerID)


# Display results
cat("Customers who bought both Electronics and Clothing:", length(both_categories_customers), "customers\n")

Customers who bought both Electronics and Clothing: 9 customers

## Part 4: Data Sorting with `arrange()`

Practice sorting data by single and multiple columns.

In [25]:
# Task 4.1: Single Column Sorting

# Sort by TotalAmount ascending
transactions_by_amount_asc <- transactions %>%
  arrange(TotalAmount)                      
print("Arranged by TotalAmount (Ascending):")
print(transactions_by_amount_asc)


# Sort by TotalAmount descending
transactions_by_amount_desc <- transactions %>%
  arrange(desc(TotalAmount))               
print("Arranged by TotalAmount (Descending):")
print(transactions_by_amount_desc)


# Display top 5 of each
cat("Lowest amounts:\n")
head(transactions_by_amount_asc %>% select(CustomerName, ProductName, TotalAmount), 5)

cat("\nHighest amounts:\n")
head(transactions_by_amount_desc %>% select(CustomerName, ProductName, TotalAmount), 5)

[1] "Arranged by TotalAmount (Ascending):"
    TransactionID CustomerID CustomerName CustomerCity     ProductName
1             315          1  Customer 95 Philadelphia   Adidas Jacket
2              14         19 Customer 100      Phoenix      Nike Shoes
3             477         72  Customer 50     New York   Adidas Jacket
4             275        100  Customer 83 Philadelphia      Samsung TV
5             282         48  Customer 69      Chicago     Dell Laptop
6             473         76  Customer 29     New York      HP Printer
7             325         26  Customer 43  Los Angeles      Samsung TV
8              38         55  Customer 61     New York   Adidas Jacket
9             464         84  Customer 83 Philadelphia      HP Printer
10             39         36  Customer 83  Los Angeles Sony Headphones
11            296         56  Customer 68      Chicago      Samsung TV
12             47         87  Customer 87      Chicago      HP Printer
13            406          7  Customer 49      Phoenix       iPhone 14
14            318         27  Customer 32      Houston       iPhone 14
15            462         73  Customer 15      Phoenix Sony Headphones
16             97          3  Customer 70  Los Angeles   Adidas Jacket
17            403         12  Customer 47     New York      Nike Shoes
18            280         17  Customer 77  Los Angeles      HP Printer
19              7         45  Customer 83     New York      HP Printer
20            208         30  Customer 74      Phoenix       iPhone 14
21            245          3  Customer 97     New York      Nike Shoes
22             33         60  Customer 65 Philadelphia       iPhone 14
23            360         39  Customer 11  Los Angeles       iPhone 14
24            356         92  Customer 67 Philadelphia Sony Headphones
25             27          6  Customer 27 Philadelphia      HP Printer
26            497         21  Customer 64      Phoenix      Nike Shoes
27            108         41  Customer 95 Philadelphia      HP Printer
28            416         39  Customer 15      Houston      Nike Shoes
29              5         86  Customer 45     New York      Nike Shoes
30             81         86  Customer 98  Los Angeles     Dell Laptop
31            130         40  Customer 97  Los Angeles     Dell Laptop
32            461         74   Customer 4      Chicago     Dell Laptop
33              2         13  Customer 63 Philadelphia      Samsung TV
34            224         31  Customer 24 Philadelphia      Samsung TV
35            307         36  Customer 98 Philadelphia      HP Printer
36            417         70  Customer 97      Phoenix     Dell Laptop
37            413         44   Customer 4  Los Angeles Sony Headphones
38            482         95  Customer 39      Chicago      Samsung TV
39             56         43  Customer 69     New York   Adidas Jacket
40             99         54  Customer 55      Chicago      Nike Shoes
41            116         22  Customer 31     New York       iPhone 14
42            157         83  Customer 46     New York      Nike Shoes
43            324          6  Customer 69     New York       iPhone 14
44             68         28  Customer 17  Los Angeles     Dell Laptop
45            466         70  Customer 94     New York Sony Headphones
46             83         65  Customer 11  Los Angeles       iPhone 14
47            433         38  Customer 27      Phoenix      Samsung TV
48            441         75  Customer 92     New York Sony Headphones
49            379        100   Customer 1      Phoenix Sony Headphones
50            447         92  Customer 96 Philadelphia      HP Printer
51            427         91  Customer 92      Phoenix Sony Headphones
52            176         31  Customer 91     New York      HP Printer
53             72         15  Customer 27 Philadelphia Sony Headphones
54            160         55  Customer 56      Chicago       iPhone 14
55            415         57  Customer 51      Chicago   Adidas Jacket
56            371         50  Customer 44      Chicago      Samsung TV
57            395         31  Customer 89     New York      Nike Shoes
58             79         52  Customer 38      Phoenix       iPhone 14
59            240         62 Customer 100      Chicago      HP Printer
60            333         54  Customer 54     New York      Nike Shoes
61            126         31  Customer 10      Chicago     Dell Laptop
62            190         56  Customer 14     New York     Dell Laptop
63            306         89  Customer 87      Phoenix      Nike Shoes
64            370         82  Customer 56  Los Angeles      HP Printer
65             87          3  Customer 37 Philadelphia     Dell Laptop
66            381         22  Customer 19 Philadelphia      Nike Shoes
67            301         23  Customer 33     New York Sony Headphones
68            226         85  Customer 23      Phoenix     Dell Laptop
69            267         90  Customer 44  Los Angeles   Adidas Jacket
70             63         88  Customer 56      Phoenix   Adidas Jacket
71            106         85  Customer 49      Chicago     Dell Laptop
72            339         41  Customer 11     New York      Nike Shoes
73             46         40  Customer 56      Houston      HP Printer
74            405          6  Customer 94  Los Angeles       iPhone 14
75            219         23  Customer 24      Phoenix   Adidas Jacket
76            250          1  Customer 83      Houston      HP Printer
77            302        100  Customer 92      Phoenix      Samsung TV
78            269         88  Customer 72  Los Angeles      Nike Shoes
79            171         31  Customer 75  Los Angeles Sony Headphones
80            194         78  Customer 15      Chicago      Samsung TV
81            351         47   Customer 6     New York      Nike Shoes
82             41         60   Customer 9      Phoenix       iPhone 14
83            149         57  Customer 92 Philadelphia     Dell Laptop
84             21         31   Customer 1      Houston      HP Printer
85            242         41   Customer 6     New York Sony Headphones
86            438         15  Customer 58 Philadelphia   Adidas Jacket
87            290         19  Customer 32      Chicago       iPhone 14
88            117         88  Customer 91     New York   Adidas Jacket
89            251         70  Customer 69      Phoenix   Adidas Jacket
90            331         52  Customer 87      Phoenix      Nike Shoes
91            412         49  Customer 79      Phoenix   Adidas Jacket
92            145         11  Customer 96 Philadelphia       iPhone 14
93            442         36  Customer 94      Phoenix     Dell Laptop
94            123         87  Customer 87      Chicago   Adidas Jacket
95             30         98  Customer 48      Houston      Samsung TV
96            161         63  Customer 81      Phoenix      Nike Shoes
97            453         66  Customer 56     New York       iPhone 14
98             67         23  Customer 12 Philadelphia     Dell Laptop
99            500         84  Customer 50     New York   Adidas Jacket
100           273         81  Customer 72     New York Sony Headphones
101           252         64  Customer 15     New York     Dell Laptop
102           434         93 Customer 100      Phoenix      Nike Shoes
103           102         38  Customer 46 Philadelphia Sony Headphones
104           352         92  Customer 59 Philadelphia Sony Headphones
105           181         17  Customer 12      Chicago       iPhone 14
106           276         35  Customer 68      Houston   Adidas Jacket
107           112         99   Customer 9      Houston      Nike Shoes
108           342         16   Customer 8  Los Angeles      Nike Shoes
109           199          9   Customer 8      Phoenix      Nike Shoes
110           310         60  Customer 43     New York      Nike Shoes
111            77         21  Customer 16      Phoenix      Samsung TV
112           263         69  Customer 14 Philadelphia   Adidas Jacket
113           486         30   Customer 1      Phoenix      Samsung TV
114           431         42  Customer 15  Los Angeles   Adidas Jacket
115           323         33  Customer 13  Los Angeles Sony Headphones
116           262          4  Customer 35 Philadelphia      Nike Shoes
117           332         42  Customer 75      Phoenix   Adidas Jacket
118           146         66  Customer 91      Houston       iPhone 14
119           492         66  Customer 43      Chicago   Adidas Jacket
120           407         30  Customer 29 Philadelphia       iPhone 14
121           409          1  Customer 32      Chicago      HP Printer
122            75         91  Customer 76     New York   Adidas Jacket
123           456         81  Customer 40 Philadelphia     Dell Laptop
124           211         27  Customer 52 Philadelphia      Samsung TV
125           288         78  Customer 21      Houston       iPhone 14
126           444         92  Customer 44     New York      HP Printer
127           249         95  Customer 94      Phoenix       iPhone 14
128           400         30  Customer 40      Chicago       iPhone 14
129           398         29  Customer 26     New York      Nike Shoes
130           270         84  Customer 90  Los Angeles   Adidas Jacket
131           319         31  Customer 74      Houston      Samsung TV
132           394         13  Customer 17      Houston      Nike Shoes
133           162         68  Customer 78     New York      Samsung TV
134            85         49  Customer 25      Houston      Nike Shoes
135           472         35  Customer 23  Los Angeles      Samsung TV
136           221         24  Customer 54     New York Sony Headphones
137           177         87  Customer 87 Philadelphia Sony Headphones
138           111         53  Customer 44     New York       iPhone 14
139           448          5  Customer 74      Houston      HP Printer
140           320         67   Customer 6      Phoenix       iPhone 14
141           485         73  Customer 57 Philadelphia Sony Headphones
142           113         98  Customer 42      Houston      HP Printer
143           114          3  Customer 26 Philadelphia      Nike Shoes
144           204         12  Customer 63  Los Angeles Sony Headphones
145           437         82  Customer 25 Philadelphia   Adidas Jacket
146           182         70  Customer 49      Phoenix       iPhone 14
147           228         28  Customer 94      Houston   Adidas Jacket
148           192         86  Customer 67 Philadelphia Sony Headphones
149           399         15  Customer 76     New York Sony Headphones
150           137         14   Customer 2 Philadelphia      HP Printer
151           330         52  Customer 81      Houston   Adidas Jacket
152           353         72  Customer 18      Phoenix     Dell Laptop
153            54         67  Customer 64      Houston      Nike Shoes
154           354         74  Customer 65  Los Angeles     Dell Laptop
155           103         41 Customer 100      Phoenix Sony Headphones
156            57         84  Customer 70      Chicago      Samsung TV
157           140         70  Customer 10      Houston      Samsung TV
158           193         77  Customer 23 Philadelphia     Dell Laptop
159           155         21  Customer 93  Los Angeles      Nike Shoes
160           241         18  Customer 85 Philadelphia     Dell Laptop
161           159         81  Customer 25      Houston Sony Headphones
162           156         86  Customer 59      Chicago      Samsung TV
163           216         33  Customer 66      Houston      Samsung TV
164           440         99  Customer 35     New York Sony Headphones
165           165         14  Customer 31     New York     Dell Laptop
166           304         28  Customer 18      Houston   Adidas Jacket
167            53         32  Customer 61     New York   Adidas Jacket
168           349         11   Customer 3  Los Angeles Sony Headphones
169            26         34   Customer 7 Philadelphia       iPhone 14
170           101          9  Customer 43      Chicago      Nike Shoes
171           463         30  Customer 45      Houston      HP Printer
172           214         49  Customer 21      Houston      Nike Shoes
173           285         40  Customer 18      Phoenix      HP Printer
174           487         68  Customer 74      Houston      Samsung TV
175            17          2  Customer 38     New York Sony Headphones
176           436          4  Customer 11      Phoenix Sony Headphones
177           260         56  Customer 54 Philadelphia   Adidas Jacket
178            94         85  Customer 17      Chicago     Dell Laptop
179           206         96  Customer 17      Houston       iPhone 14
180           480         70  Customer 30      Houston      Nike Shoes
181           223         41  Customer 73      Houston Sony Headphones
182           230          5  Customer 92     New York      Samsung TV
183           255         78  Customer 64      Houston     Dell Laptop
184           489         60  Customer 31      Chicago       iPhone 14
185            35         24  Customer 47     New York      Samsung TV
186           110         51  Customer 59      Chicago      Samsung TV
187           322         83  Customer 27  Los Angeles Sony Headphones
188           247          7  Customer 37      Phoenix      HP Printer
189           209         27  Customer 18 Philadelphia      HP Printer
190           454         23  Customer 71      Phoenix      HP Printer
191           105         81  Customer 53 Philadelphia       iPhone 14
192           107         85  Customer 61 Philadelphia   Adidas Jacket
193           186         76  Customer 87 Philadelphia      Samsung TV
194            82         69  Customer 98      Chicago   Adidas Jacket
195           197         30  Customer 39      Houston     Dell Laptop
196            11        100  Customer 95 Philadelphia      HP Printer
197           471         20  Customer 51     New York      Nike Shoes
198           305         80  Customer 27      Houston      HP Printer
199           389         89   Customer 1     New York Sony Headphones
200           175         89  Customer 88     New York      Nike Shoes
201           238          7  Customer 39      Chicago Sony Headphones
202           383         74  Customer 76  Los Angeles      Samsung TV
203            60         61  Customer 77  Los Angeles      Nike Shoes
204           298         57  Customer 71     New York      Samsung TV
205            15          1  Customer 52     New York      Nike Shoes
206           183          5   Customer 4 Philadelphia      Nike Shoes
207           329         20  Customer 66  Los Angeles      Nike Shoes
208           222         62  Customer 25      Chicago      Samsung TV
209           168         11  Customer 90     New York      HP Printer
210           191        100  Customer 53      Phoenix      HP Printer
211             1         81  Customer 39      Chicago   Adidas Jacket
212            10         55  Customer 24      Chicago Sony Headphones
213           397         99  Customer 37  Los Angeles       iPhone 14
214           135         14  Customer 98      Houston      HP Printer
215           205         89  Customer 87      Phoenix   Adidas Jacket
216           132         80  Customer 44  Los Angeles   Adidas Jacket
217           279         93  Customer 91      Chicago      Samsung TV
218           445         57  Customer 25 Philadelphia       iPhone 14
219           300         85  Customer 82 Philadelphia      Samsung TV
220           227         20  Customer 18  Los Angeles   Adidas Jacket
221           420         24  Customer 97     New York   Adidas Jacket
222           357         53  Customer 21     New York     Dell Laptop
223            93         36  Customer 74      Chicago   Adidas Jacket
224           120         29  Customer 22  Los Angeles      Samsung TV
225           143         91  Customer 66      Chicago      Samsung TV
226           460         73  Customer 40  Los Angeles      Nike Shoes
227            88         96  Customer 42      Chicago   Adidas Jacket
228           287         11  Customer 65  Los Angeles      Samsung TV
229           166         78   Customer 6  Los Angeles     Dell Laptop
230           316         65  Customer 98  Los Angeles Sony Headphones
231           498         89  Customer 25     New York Sony Headphones
232            28         54  Customer 41  Los Angeles   Adidas Jacket
233           299         36  Customer 16      Phoenix      Samsung TV
234           490         83  Customer 94  Los Angeles      Nike Shoes
235           402         44  Customer 84  Los Angeles      Nike Shoes
236           174        100  Customer 38      Houston      HP Printer
237           265         79  Customer 92 Philadelphia      Samsung TV
238           258         43  Customer 98 Philadelphia       iPhone 14
239            91         54  Customer 32      Chicago      HP Printer
240            96         90  Customer 81     New York      Samsung TV
241           452         33  Customer 16      Phoenix     Dell Laptop
242            86         28   Customer 4 Philadelphia   Adidas Jacket
243           308          9  Customer 11      Phoenix      HP Printer
244           185         43  Customer 21      Phoenix Sony Headphones
245           283         77  Customer 44      Phoenix      Samsung TV
246           350          1  Customer 46     New York      Nike Shoes
247           364         67  Customer 95      Houston      HP Printer
248            40         30  Customer 73      Houston Sony Headphones
249           326         43   Customer 2     New York      Nike Shoes
250           429         25  Customer 48     New York      HP Printer
251           363         69  Customer 14  Los Angeles      HP Printer
252           115         20  Customer 80      Phoenix Sony Headphones
253           239         79  Customer 10      Houston      HP Printer
254           163         74  Customer 20     New York      Nike Shoes
255            65         94   Customer 5      Chicago      Samsung TV
256           188         35  Customer 87      Phoenix Sony Headphones
257           338         29  Customer 71      Phoenix      Samsung TV
258            98         46  Customer 68      Chicago      Nike Shoes
259           309         67  Customer 37      Phoenix      Nike Shoes
260           314         73  Customer 33  Los Angeles     Dell Laptop
261           313         36  Customer 98      Houston      Samsung TV
262           426         86  Customer 25  Los Angeles     Dell Laptop
263           358         15   Customer 2  Los Angeles Sony Headphones
264            50         92  Customer 83      Chicago      Nike Shoes
265            43         27  Customer 74      Houston Sony Headphones
266           443         72  Customer 13  Los Angeles       iPhone 14
267           220         78   Customer 9 Philadelphia      Samsung TV
268           233         23  Customer 47     New York   Adidas Jacket
269           151         88  Customer 96      Chicago Sony Headphones
270            19          7   Customer 1      Phoenix Sony Headphones
271           292         29  Customer 46      Houston      HP Printer
272           423         40  Customer 74  Los Angeles     Dell Laptop
273           121         76  Customer 63      Houston Sony Headphones
274           215         51  Customer 76      Houston      HP Printer
275           414         12  Customer 95     New York   Adidas Jacket
276           488         82  Customer 29      Chicago Sony Headphones
277           391         18  Customer 76 Philadelphia      HP Printer
278           496         92  Customer 25      Chicago       iPhone 14
279           213         70  Customer 92      Phoenix       iPhone 14
280           200         15  Customer 75      Houston      Samsung TV

    TransactionID CustomerID CustomerName CustomerCity     ProductName
1             150         64  Customer 60     New York Sony Headphones
2              61         87  Customer 28     New York     Dell Laptop
3             154         18  Customer 81      Phoenix Sony Headphones
4             187         64  Customer 79      Phoenix       iPhone 14
5             136         99  Customer 20      Phoenix      HP Printer
6             297          7  Customer 18      Chicago       iPhone 14
7             378         53  Customer 83 Philadelphia       iPhone 14
8              16         78  Customer 20      Chicago      HP Printer
9             479         83  Customer 10      Houston     Dell Laptop
10             84         41  Customer 14      Phoenix       iPhone 14
11            232         91  Customer 11     New York     Dell Laptop
12            341         47  Customer 36      Houston Sony Headphones
13            384         42  Customer 97      Chicago     Dell Laptop
14            468         32  Customer 47  Los Angeles     Dell Laptop
15            244         79  Customer 49      Chicago     Dell Laptop
16            345         44  Customer 27  Los Angeles      Samsung TV
17            231         16  Customer 90  Los Angeles   Adidas Jacket
18            142         75  Customer 76     New York Sony Headphones
19            212         79  Customer 87  Los Angeles     Dell Laptop
20            428         73  Customer 53      Phoenix      Samsung TV
21            430         36  Customer 85  Los Angeles       iPhone 14
22            196         11  Customer 70      Chicago      Nike Shoes
23            104         52  Customer 29      Phoenix     Dell Laptop
24            446         65   Customer 6      Phoenix      Samsung TV
25            421          4  Customer 18     New York      Nike Shoes
26             22         80   Customer 4     New York       iPhone 14
27             62         32  Customer 71      Chicago      Samsung TV
28            243         46  Customer 85  Los Angeles Sony Headphones
29            261         27  Customer 80      Phoenix      HP Printer
30            392         67  Customer 50     New York      Nike Shoes
31             32         21  Customer 62      Chicago Sony Headphones
32            122         35  Customer 74     New York   Adidas Jacket
33             71         20  Customer 53 Philadelphia     Dell Laptop
34            455          3  Customer 67      Phoenix       iPhone 14
35            317         73  Customer 11      Chicago      Nike Shoes
36            237         62  Customer 54      Houston      HP Printer
37            469         85  Customer 31  Los Angeles Sony Headphones
38             51         20  Customer 26      Phoenix      HP Printer
39            475         95  Customer 63  Los Angeles       iPhone 14
40            217         85  Customer 53 Philadelphia      HP Printer
41             29          3  Customer 23     New York      Samsung TV
42            499         77  Customer 99      Chicago      HP Printer
43            478         84  Customer 24      Houston      Nike Shoes
44            286         34  Customer 21  Los Angeles      Nike Shoes
45            266         33  Customer 98 Philadelphia     Dell Laptop
46            100         66  Customer 65      Phoenix     Dell Laptop
47            184         83  Customer 18  Los Angeles      HP Printer
48             69         70  Customer 49      Chicago      Nike Shoes
49            494         93  Customer 22      Houston      Samsung TV
50            144         93   Customer 5 Philadelphia      Samsung TV
51            264         76  Customer 54      Houston      Nike Shoes
52            170         95  Customer 15 Philadelphia      Samsung TV
53            312         10  Customer 22     New York      Samsung TV
54            328         24  Customer 51     New York      Nike Shoes
55             95         51  Customer 14      Phoenix   Adidas Jacket
56              9         13  Customer 69      Houston       iPhone 14
57            178         42   Customer 3     New York Sony Headphones
58            450         69  Customer 51      Chicago      HP Printer
59             13         56  Customer 62      Phoenix     Dell Laptop
60            259         23  Customer 16 Philadelphia   Adidas Jacket
61            393         98  Customer 96      Phoenix      Samsung TV
62            404         86  Customer 41  Los Angeles     Dell Laptop
63            467         38   Customer 4  Los Angeles      Nike Shoes
64            133         65  Customer 99 Philadelphia Sony Headphones
65            169         89  Customer 91      Chicago Sony Headphones
66            335         64  Customer 88      Chicago     Dell Laptop
67            291          9  Customer 20      Chicago   Adidas Jacket
68            180         50  Customer 18 Philadelphia     Dell Laptop
69            484         50  Customer 85      Houston      Nike Shoes
70            457         30  Customer 54      Chicago Sony Headphones
71            281          7  Customer 18      Houston Sony Headphones
72            367         60  Customer 21      Chicago      Samsung TV
73            388         43  Customer 58     New York      HP Printer
74              3         18  Customer 98      Chicago   Adidas Jacket
75            277         48  Customer 52      Phoenix      HP Printer
76            293         73  Customer 65     New York       iPhone 14
77            474        100  Customer 94      Chicago     Dell Laptop
78            158         66  Customer 83  Los Angeles   Adidas Jacket
79            435         58  Customer 94      Houston      Samsung TV
80            138         59  Customer 24 Philadelphia Sony Headphones
81            278         73  Customer 47     New York      Samsung TV
82            432         62   Customer 4  Los Angeles Sony Headphones
83            425         81  Customer 98 Philadelphia Sony Headphones
84            257          5  Customer 45      Houston      HP Printer
85             52         31  Customer 33     New York   Adidas Jacket
86            366         77  Customer 41 Philadelphia Sony Headphones
87            334         77  Customer 99      Houston      Samsung TV
88            129         88  Customer 54  Los Angeles   Adidas Jacket
89            321         43  Customer 84      Chicago      Nike Shoes
90            355          6   Customer 3      Phoenix      Samsung TV
91            458         63  Customer 92      Houston       iPhone 14
92            344         54  Customer 44      Houston Sony Headphones
93            172         31  Customer 90      Chicago     Dell Laptop
94             49         17  Customer 73 Philadelphia     Dell Laptop
95            336         82  Customer 46  Los Angeles      Nike Shoes
96             31         11  Customer 30      Chicago   Adidas Jacket
97            390         91  Customer 48      Phoenix      Samsung TV
98            127         54  Customer 77      Phoenix   Adidas Jacket
99             12         89  Customer 22 Philadelphia   Adidas Jacket
100            45          1  Customer 28 Philadelphia       iPhone 14
101           376         81  Customer 45 Philadelphia   Adidas Jacket
102           148         76  Customer 75     New York       iPhone 14
103            80         12  Customer 87      Houston       iPhone 14
104           385         28  Customer 26      Houston       iPhone 14
105            20         27  Customer 57      Chicago     Dell Laptop
106           189         15  Customer 89 Philadelphia      Nike Shoes
107           362         47  Customer 11  Los Angeles      HP Printer
108           153         97  Customer 13      Houston      Samsung TV
109           368         59  Customer 82      Phoenix      Samsung TV
110            24         88  Customer 30      Phoenix      Nike Shoes
111           386         72  Customer 13     New York      Nike Shoes
112           327         52  Customer 91     New York      Samsung TV
113           382         16  Customer 62     New York       iPhone 14
114           418         63  Customer 47 Philadelphia      Nike Shoes
115            42         59  Customer 20      Chicago Sony Headphones
116           481         67  Customer 87 Philadelphia      HP Printer
117           202          4  Customer 17 Philadelphia   Adidas Jacket
118           139         67  Customer 82  Los Angeles Sony Headphones
119           253         30  Customer 90      Houston     Dell Laptop
120            70         61  Customer 38  Los Angeles       iPhone 14
121           483         94  Customer 60      Phoenix Sony Headphones
122           396         78  Customer 99      Houston   Adidas Jacket
123           459         95  Customer 32      Chicago Sony Headphones
124           124         78  Customer 69      Phoenix     Dell Laptop
125           229         37   Customer 9     New York     Dell Laptop
126            44          7  Customer 42      Chicago       iPhone 14
127           225          3  Customer 15     New York Sony Headphones
128           274         91   Customer 1      Houston   Adidas Jacket
129           198         67  Customer 61      Chicago   Adidas Jacket
130             6         37   Customer 8 Philadelphia   Adidas Jacket
131            78         59  Customer 51  Los Angeles       iPhone 14
132           164         43  Customer 37      Phoenix      Samsung TV
133           152         24  Customer 83 Philadelphia      HP Printer
134           268         71  Customer 81      Chicago      HP Printer
135           294          2  Customer 20  Los Angeles      Nike Shoes
136           410        100  Customer 33      Houston      Samsung TV
137            92          6  Customer 55     New York       iPhone 14
138           470         26  Customer 92      Phoenix      HP Printer
139           284         82  Customer 48  Los Angeles      Nike Shoes
140           359         90  Customer 73 Philadelphia      HP Printer
141           493         75  Customer 50  Los Angeles     Dell Laptop
142            37         66  Customer 93      Phoenix      Nike Shoes
143           374         82  Customer 57 Philadelphia     Dell Laptop
144           380         70   Customer 1  Los Angeles      HP Printer
145           125         57  Customer 49  Los Angeles       iPhone 14
146           271         89  Customer 43      Phoenix      HP Printer
147           408         32  Customer 63     New York      Nike Shoes
148           173         43  Customer 71      Houston      Nike Shoes
149           118         43  Customer 53 Philadelphia     Dell Laptop
150           246         51  Customer 11      Chicago   Adidas Jacket
151           419         39  Customer 84     New York      HP Printer
152           369         61  Customer 19      Houston     Dell Laptop
153           119         49  Customer 53  Los Angeles      HP Printer
154           361         52  Customer 40      Phoenix       iPhone 14
155           234         96  Customer 91      Chicago Sony Headphones
156           439         91  Customer 30      Chicago     Dell Laptop
157           128         39  Customer 57     New York   Adidas Jacket
158           337         29  Customer 80  Los Angeles   Adidas Jacket
159           254         67  Customer 99      Houston      HP Printer
160           411         91   Customer 6     New York      HP Printer
161           236          6  Customer 29  Los Angeles     Dell Laptop
162           109         60  Customer 64      Chicago   Adidas Jacket
163           248         98  Customer 23  Los Angeles   Adidas Jacket
164            18          5  Customer 15      Phoenix     Dell Laptop
165           203         32  Customer 28      Phoenix   Adidas Jacket
166           348         94  Customer 47      Phoenix       iPhone 14
167           343         68  Customer 27      Houston     Dell Laptop
168           491         14  Customer 75      Chicago      HP Printer
169           340         54  Customer 60      Houston     Dell Laptop
170           365         40   Customer 1     New York Sony Headphones
171           147         60  Customer 78      Phoenix      Nike Shoes
172            25         97  Customer 17     New York       iPhone 14
173           167         26  Customer 76      Houston Sony Headphones
174           311         55  Customer 70      Houston     Dell Laptop
175           303         95  Customer 36      Phoenix      Nike Shoes
176           375         51  Customer 64      Chicago      HP Printer
177           372         29  Customer 72 Philadelphia       iPhone 14
178           449         13  Customer 99      Chicago       iPhone 14
179           201          7  Customer 87 Philadelphia       iPhone 14
180           465         50  Customer 69      Houston      HP Printer
181            89         61  Customer 18     New York      HP Printer
182           451         18  Customer 20      Houston      HP Printer
183           141         45  Customer 32     New York   Adidas Jacket
184            76         35  Customer 83      Houston       iPhone 14
185            55         17  Customer 53      Phoenix Sony Headphones
186            66         21  Customer 45      Chicago   Adidas Jacket
187           218         24  Customer 39      Houston     Dell Laptop
188            58         31  Customer 68      Houston   Adidas Jacket
189            59          9  Customer 25     New York      Samsung TV
190           235         94  Customer 12      Phoenix      Samsung TV
191           295         40  Customer 30  Los Angeles      Nike Shoes
192           401         13  Customer 13 Philadelphia     Dell Laptop
193           289         16  Customer 27      Phoenix      Samsung TV
194            48         71  Customer 18 Philadelphia       iPhone 14
195            90         12  Customer 11      Chicago     Dell Laptop
196           387         91  Customer 85      Chicago      HP Printer
197           179         14  Customer 47  Los Angeles      HP Printer
198           346         64  Customer 46      Houston      Nike Shoes
199           495         48  Customer 25      Chicago Sony Headphones
200           422         68  Customer 39     New York       iPhone 14
201            64          9  Customer 68      Houston   Adidas Jacket
202           347         54  Customer 71      Houston     Dell Laptop
203           476          3  Customer 43      Chicago Sony Headphones
204            73         50  Customer 50      Chicago Sony Headphones
205           207         79  Customer 69 Philadelphia       iPhone 14
206            23         57  Customer 50      Chicago      HP Printer
207           373         24   Customer 5  Los Angeles      HP Printer
208           272         20  Customer 23      Chicago      HP Printer
209           210          8  Customer 59      Houston     Dell Laptop
210            34         62  Customer 26      Houston   Adidas Jacket
211           134         22  Customer 49     New York      Samsung TV
212           424          4   Customer 3     New York Sony Headphones
213             4         76  Customer 39      Houston     Dell Laptop
214           256         51  Customer 58  Los Angeles     Dell Laptop
215           377         32  Customer 75      Phoenix      HP Printer
216            74         57  Customer 88 Philadelphia      Samsung TV
217            36         47  Customer 82     New York   Adidas Jacket
218             8         11  Customer 60      Chicago      Samsung TV
219           195         70  Customer 37     New York   Adidas Jacket
220           131         98  Customer 70      Houston   Adidas Jacket
221           200         15  Customer 75      Houston      Samsung TV
222           213         70  Customer 92      Phoenix       iPhone 14
223           496         92  Customer 25      Chicago       iPhone 14
224           391         18  Customer 76 Philadelphia      HP Printer
225           488         82  Customer 29      Chicago Sony Headphones
226           414         12  Customer 95     New York   Adidas Jacket
227           215         51  Customer 76      Houston      HP Printer
228           121         76  Customer 63      Houston Sony Headphones
229           423         40  Customer 74  Los Angeles     Dell Laptop
230           292         29  Customer 46      Houston      HP Printer
231            19          7   Customer 1      Phoenix Sony Headphones
232           151         88  Customer 96      Chicago Sony Headphones
233           233         23  Customer 47     New York   Adidas Jacket
234           220         78   Customer 9 Philadelphia      Samsung TV
235           443         72  Customer 13  Los Angeles       iPhone 14
236            43         27  Customer 74      Houston Sony Headphones
237            50         92  Customer 83      Chicago      Nike Shoes
238           358         15   Customer 2  Los Angeles Sony Headphones
239           426         86  Customer 25  Los Angeles     Dell Laptop
240           313         36  Customer 98      Houston      Samsung TV
241           314         73  Customer 33  Los Angeles     Dell Laptop
242           309         67  Customer 37      Phoenix      Nike Shoes
243            98         46  Customer 68      Chicago      Nike Shoes
244           338         29  Customer 71      Phoenix      Samsung TV
245           188         35  Customer 87      Phoenix Sony Headphones
246            65         94   Customer 5      Chicago      Samsung TV
247           163         74  Customer 20     New York      Nike Shoes
248           239         79  Customer 10      Houston      HP Printer
249           115         20  Customer 80      Phoenix Sony Headphones
250           363         69  Customer 14  Los Angeles      HP Printer
251           429         25  Customer 48     New York      HP Printer
252           326         43   Customer 2     New York      Nike Shoes
253            40         30  Customer 73      Houston Sony Headphones
254           364         67  Customer 95      Houston      HP Printer
255           350          1  Customer 46     New York      Nike Shoes
256           283         77  Customer 44      Phoenix      Samsung TV
257           185         43  Customer 21      Phoenix Sony Headphones
258           308          9  Customer 11      Phoenix      HP Printer
259            86         28   Customer 4 Philadelphia   Adidas Jacket
260           452         33  Customer 16      Phoenix     Dell Laptop
261            96         90  Customer 81     New York      Samsung TV
262            91         54  Customer 32      Chicago      HP Printer
263           258         43  Customer 98 Philadelphia       iPhone 14
264           265         79  Customer 92 Philadelphia      Samsung TV
265           174        100  Customer 38      Houston      HP Printer
266           402         44  Customer 84  Los Angeles      Nike Shoes
267           490         83  Customer 94  Los Angeles      Nike Shoes
268           299         36  Customer 16      Phoenix      Samsung TV
269            28         54  Customer 41  Los Angeles   Adidas Jacket
270           498         89  Customer 25     New York Sony Headphones
271           316         65  Customer 98  Los Angeles Sony Headphones
272           166         78   Customer 6  Los Angeles     Dell Laptop
273           287         11  Customer 65  Los Angeles      Samsung TV
274            88         96  Customer 42      Chicago   Adidas Jacket
275           460         73  Customer 40  Los Angeles      Nike Shoes
276           143         91  Customer 66      Chicago      Samsung TV
277           120         29  Customer 22  Los Angeles      Samsung TV
278            93         36  Customer 74      Chicago   Adidas Jacket
279           357         53  Customer 21     New York     Dell Laptop
280           420         24  Customer 97     New York   Adidas Jacket

  CustomerName ProductName   TotalAmount
1 Customer 95  Adidas Jacket 27.66
2 Customer 100 Nike Shoes    32.29
3 Customer 50  Adidas Jacket 35.01
4 Customer 83  Samsung TV    36.37
5 Customer 69  Dell Laptop   37.33

Highest amounts:

  CustomerName ProductName     TotalAmount
1 Customer 60  Sony Headphones 1499.52
2 Customer 28  Dell Laptop     1491.96
3 Customer 81  Sony Headphones 1491.62
4 Customer 79  iPhone 14       1488.95
5 Customer 20  HP Printer      1487.44

In [26]:
# Task 4.2: Multiple Column Sorting
# Sort by CustomerCity (ascending), then by TotalAmount (descending)

transactions_by_city_amount <- transactions %>%
  arrange(CustomerCity, desc(TotalAmount))


# Display first 10 rows
cat("Transactions sorted by city, then amount:\n")
head(transactions_by_city_amount %>% select(CustomerCity, CustomerName, ProductName, TotalAmount), 10)

Transactions sorted by city, then amount:

   CustomerCity CustomerName ProductName     TotalAmount
1  Chicago      Customer 18  iPhone 14       1487.43
2  Chicago      Customer 20  HP Printer      1476.49
3  Chicago      Customer 97  Dell Laptop     1459.42
4  Chicago      Customer 49  Dell Laptop     1453.94
5  Chicago      Customer 70  Nike Shoes      1428.35
6  Chicago      Customer 71  Samsung TV      1424.38
7  Chicago      Customer 62  Sony Headphones 1416.35
8  Chicago      Customer 11  Nike Shoes      1407.51
9  Chicago      Customer 99  HP Printer      1388.73
10 Chicago      Customer 49  Nike Shoes      1370.57

In [29]:
# Task 4.3: Date-Based Sorting
# Sort by TransactionDate chronologically (oldest first)

transactions_chronological <- transactions %>%
  arrange(TransactionDate)


# Display first 5 transactions chronologically
cat("Earliest transactions:\n")
head(transactions_chronological %>% select(TransactionDate, CustomerName, ProductName, TotalAmount), 5)

Earliest transactions:

  TransactionDate CustomerName ProductName     TotalAmount
1 2024-01-01      Customer 62  Sony Headphones 1416.35
2 2024-01-01      Customer 99  Sony Headphones 1326.27
3 2024-01-02      Customer 83  Nike Shoes       808.93
4 2024-01-02      Customer 61  Adidas Jacket    502.72
5 2024-01-02      Customer 69  Adidas Jacket    277.70

## Part 5: Chaining Operations

Combine multiple dplyr operations using the pipe operator.

In [30]:
premium_purchases <- transactions %>%
  
  filter(TotalAmount > 75) %>%
  select(CustomerName, ProductName, TotalAmount) %>%
  arrange(desc(TotalAmount))

# Display results
cat("Premium purchases (>$75):\n")
head(premium_purchases, 10)

Premium purchases (>$75):

   CustomerName ProductName     TotalAmount
1  Customer 60  Sony Headphones 1499.52
2  Customer 28  Dell Laptop     1491.96
3  Customer 81  Sony Headphones 1491.62
4  Customer 79  iPhone 14       1488.95
5  Customer 20  HP Printer      1487.44
6  Customer 18  iPhone 14       1487.43
7  Customer 83  iPhone 14       1484.31
8  Customer 20  HP Printer      1476.49
9  Customer 10  Dell Laptop     1473.27
10 Customer 14  iPhone 14       1471.59

In [31]:
# Task 5.2: Complex Chain
# Filter for Electronics/Computers, select columns, arrange by date/amount, keep top 20

recent_tech_purchases <- transactions %>%
  filter(ProductCategory %in% c("Electronics", "Computers")) %>%  # Step 1: Filter for tech categories
  select(TransactionDate, CustomerName, ProductName, TotalAmount) %>%  # Step 2: Select specific columns
  arrange(desc(TransactionDate), desc(TotalAmount)) %>%  # Step 3: Sort by date (newest first), then amount (highest first)
  head(20) 


# Display results
cat("Recent tech purchases (top 20):\n")
print(recent_tech_purchases)

Recent tech purchases (top 20):
   TransactionDate CustomerName     ProductName TotalAmount
1       2024-12-30  Customer 27 Sony Headphones      539.52
2       2024-12-30  Customer 33 Sony Headphones      206.62
3       2024-12-25  Customer 39      Samsung TV      121.22
4       2024-12-24  Customer 25 Sony Headphones      700.12
5       2024-12-23  Customer 85       iPhone 14     1433.31
6       2024-12-19  Customer 73     Dell Laptop     1220.59
7       2024-12-13  Customer 17     Dell Laptop      140.76
8       2024-12-12   Customer 6      Nike Shoes      246.96
9       2024-12-11  Customer 54   Adidas Jacket     1231.83
10      2024-12-10  Customer 19      Nike Shoes      192.98
11      2024-12-07  Customer 12       iPhone 14      314.66
12      2024-12-06  Customer 85      HP Printer      929.88
13      2024-12-04  Customer 39     Dell Laptop      957.29
14      2024-12-04  Customer 12      Samsung TV      940.10
15      2024-12-02  Customer 90   Adidas Jacket     1445.64
16      2024-12-02  Customer 54 Sony Headphones      424.71
17      2024-12-02  Customer 24      Samsung TV      116.06
18      2024-11-30  Customer 36 Sony Headphones     1469.91
19      2024-11-28  Customer 13     Dell Laptop      937.37
20      2024-11-28  Customer 33     Dell Laptop      798.78

In [32]:
# Task 5.3: Business Intelligence Chain
# Identify high-value repeat customers (TotalAmount > $200)

high_value_customers <- transactions %>%
  filter(TotalAmount > 200) %>%
  select(CustomerName, ProductName, TotalAmount, TransactionDate) %>%
  arrange(desc(TotalAmount))


# Display results
cat("High-value customers:\n")
head(high_value_customers, 15)

High-value customers:

   CustomerName ProductName     TotalAmount TransactionDate
1  Customer 60  Sony Headphones 1499.52     2024-03-03
2  Customer 28  Dell Laptop     1491.96     2024-08-15
3  Customer 81  Sony Headphones 1491.62     2024-10-18
4  Customer 79  iPhone 14       1488.95     2024-10-23
5  Customer 20  HP Printer      1487.44     2024-05-02
6  Customer 18  iPhone 14       1487.43     2024-07-15
7  Customer 83  iPhone 14       1484.31     2024-12-24
8  Customer 20  HP Printer      1476.49     2024-05-29
9  Customer 10  Dell Laptop     1473.27     2024-04-14
10 Customer 14  iPhone 14       1471.59     2024-11-16
11 Customer 11  Dell Laptop     1470.30     2024-11-25
12 Customer 36  Sony Headphones 1469.91     2024-11-30
13 Customer 97  Dell Laptop     1459.42     2024-10-28
14 Customer 47  Dell Laptop     1456.72     2024-02-02
15 Customer 49  Dell Laptop     1453.94     2024-07-29

## Part 6: Data Analysis Questions

Answer the following questions using the datasets you've created.

In [ ]:
# Question 6.1: Transaction Volume
# Count transactions in each filtered dataset

cat("Transaction counts by dataset:\n")
cat("High value transactions:", nrow(high_value_transactions), "\n")
cat("Electronics transactions:", nrow(electronics_transactions), "\n")
cat("NY bulk purchases:", nrow(ny_bulk_purchases), "\n")
cat("Entertainment transactions:", nrow(entertainment_transactions), "\n")
cat("March transactions:", nrow(march_transactions), "\n")
cat("Premium purchases:", nrow(premium_purchases), "\n")
cat("Recent tech purchases:", nrow(recent_tech_purchases), "\n")
cat("High value customers:", nrow(high_value_customers), "\n")

In [33]:
# Question 6.2: Top Customers
# Find the customer who appears most frequently in high_value_customers

if(nrow(high_value_customers) > 0) {
  customer_frequency <- high_value_customers %>%
    group_by(CustomerName) %>%
    summarise(frequency = n()) %>%
    arrange(desc(frequency))   
  
  
  cat("Most frequent high-value customer:\n")
  print(customer_frequency)
} else {
  cat("No high-value customers found\n")
}

Most frequent high-value customer:
# A tibble: 98 × 2
   CustomerName frequency
   <chr>            <int>
 1 Customer 18         12
 2 Customer 25         10
 3 Customer 87         10
 4 Customer 11          8
 5 Customer 53          8
 6 Customer 98          8
 7 Customer 1           7
 8 Customer 20          7
 9 Customer 47          7
10 Customer 74          7
# ℹ 88 more rows

In [ ]:
# Question 6.3: Product Analysis
# Find top 5 most expensive transactions in entertainment_transactions

if(nrow(entertainment_transactions) > 0) {
  top_entertainment <- entertainment_transactions %>%
    # Your code here:
  
  
  cat("Top 5 most expensive entertainment transactions:\n")
  print(top_entertainment)
} else {
  cat("No entertainment transactions found\n")
}

In [35]:
# Question 6.4: Geographic Analysis
# Find the city with the highest single transaction amount

highest_transaction_by_city <- transactions_by_city_amount %>%
  arrange(desc(TotalAmount)) %>%
  head(5)

cat("City with highest single transaction:\n")
print(highest_transaction_by_city)

City with highest single transaction:
  TransactionID CustomerID CustomerName CustomerCity     ProductName
1           150         64  Customer 60     New York Sony Headphones
2            61         87  Customer 28     New York     Dell Laptop
3           154         18  Customer 81      Phoenix Sony Headphones
4           187         64  Customer 79      Phoenix       iPhone 14
5           136         99  Customer 20      Phoenix      HP Printer
  ProductCategory TotalAmount Quantity TransactionDate
1     Electronics     1499.52        2      2024-03-03
2       Computers     1491.96        7      2024-08-15
3           Books     1491.62        3      2024-10-18
4       Computers     1488.95        4      2024-10-23
5     Electronics     1487.44        1      2024-05-02

## Part 7: Reflection Questions

Please answer the following questions in the markdown cells below.

### Question 7.1: Pipe Operator Benefits

**How does using the pipe operator (`%>%`) improve code readability compared to nested function calls? Provide a specific example from your homework.**

Your answer here: It makes the code look more organized and easier to read. Not only does writing nested functions make it look messy, but it also makes it harder to debug and find problems within the code.

### Question 7.2: Filtering Strategy

**When filtering data for business analysis, what are the trade-offs between being very specific (many conditions) versus being more general (fewer conditions)? How might this affect your insights?**

Your answer here: By being very specific, we are only seeing a very specific part of the information through a microscope, potentially missing out on other important insights. By being more general, we can see the bigger picture, but we might miss out on some important details that could be crucial for decision-making in business.

### Question 7.3: Sorting Importance

**Why is data sorting important in business analytics? Provide three specific business scenarios where sorting data would be crucial for decision-making.**

Your answer here:

1. Managing inventory by sorting products based on sales (bestseller vs slowseller) and identify which items need restocking.
2. Sales performance of a set of products
3. Customer Relationship Management (CRM) by sorting customers based on their purchase history and frequency to identify high-value customers for targeted marketing campaigns.

### Question 7.4: Real-World Application

**Describe a real business scenario where you might need to combine `select()`, `filter()`, and `arrange()` operations. What insights would you be trying to gain?**

Your answer here: A real business scenario could be analyzing customer purchase behavior during a holiday sale. By selecting relevant columns such as CustomerName, ProductName, TotalAmount, and TransactionDate, filtering for transactions that occurred during the sale period and had a TotalAmount greater than a certain threshold, and arranging the results by TotalAmount in descending order, we could identify high-value customers and popular products. This insight would help in tailoring marketing strategies and inventory management for future sales events.

## Summary and Submission

### What You've Learned

In this homework, you've practiced:
- Using `select()` for column selection with various methods
- Using `filter()` for row filtering with single and multiple conditions
- Using `arrange()` for sorting data by single and multiple columns
- Chaining operations with the pipe operator (`%>%`)
- Analyzing business data to generate insights

### Submission Checklist

Before submitting, ensure you have:
- [ ] Completed all code tasks
- [ ] Run all cells successfully
- [ ] Answered all reflection questions
- [ ] Used proper commenting in your code
- [ ] Used the pipe operator where appropriate
- [ ] Verified your results make sense

### Next Steps

In the next lesson, you'll learn about:
- `mutate()` for creating new columns
- `summarize()` for calculating summary statistics
- `group_by()` for grouped operations
- Advanced data transformation techniques